export const UNIVERSITIES_DATA = [
  // SAUDI ARABIA
  {
    name: "King Fahd University of Petroleum & Minerals (KFUPM)",
    country: "Saudi Arabia",
    city: "Dhahran",
    worldRanking: 101,
    localRanking: 1,
    type: "public" as const,
    website: "https://www.kfupm.edu.sa",
  },
  {
    name: "King Abdulaziz University (KAU)",
    country: "Saudi Arabia",
    city: "Jeddah",
    worldRanking: 143,
    localRanking: 2,
    type: "public" as const,
    website: "https://www.kau.edu.sa",
  },
  {
    name: "King Saud University (KSU)",
    country: "Saudi Arabia",
    city: "Riyadh",
    worldRanking: 203,
    localRanking: 3,
    type: "public" as const,
    website: "https://ksu.edu.sa",
  },
  {
    name: "King Abdullah University of Science and Technology (KAUST)",
    country: "Saudi Arabia",
    city: "Thuwal",
    worldRanking: 150,
    localRanking: 4,
    type: "public" as const,
    website: "https://www.kaust.edu.sa",
  },
  {
    name: "Imam Abdulrahman Bin Faisal University (IAU)",
    country: "Saudi Arabia",
    city: "Dammam",
    worldRanking: 501,
    localRanking: 5,
    type: "public" as const,
    website: "https://www.iau.edu.sa",
  },
  {
    name: "King Khalid University",
    country: "Saudi Arabia",
    city: "Abha",
    worldRanking: 601,
    localRanking: 6,
    type: "public" as const,
    website: "https://www.kku.edu.sa",
  },
  {
    name: "Prince Mohammad Bin Fahd University",
    country: "Saudi Arabia",
    city: "Al Khobar",
    worldRanking: 651,
    localRanking: 7,
    type: "private" as const,
    website: "https://www.pmu.edu.sa",
  },
  {
    name: "Umm Al-Qura University",
    country: "Saudi Arabia",
    city: "Makkah",
    worldRanking: 801,
    localRanking: 8,
    type: "public" as const,
    website: "https://uqu.edu.sa",
  },
  {
    name: "King Faisal University",
    country: "Saudi Arabia",
    city: "Al-Ahsa",
    worldRanking: 1001,
    localRanking: 9,
    type: "public" as const,
    website: "https://www.kfu.edu.sa",
  },
  {
    name: "Princess Nourah bint Abdulrahman University",
    country: "Saudi Arabia",
    city: "Riyadh",
    worldRanking: 1001,
    localRanking: 10,
    type: "public" as const,
    website: "https://www.pnu.edu.sa",
  },
  {
    name: "Alfaisal University",
    country: "Saudi Arabia",
    city: "Riyadh",
    worldRanking: 1001,
    localRanking: 11,
    type: "private" as const,
    website: "https://alfaisal.edu",
  },
  {
    name: "Qassim University",
    country: "Saudi Arabia",
    city: "Buraidah",
    worldRanking: 1201,
    localRanking: 12,
    type: "public" as const,
    website: "https://www.qu.edu.sa",
  },
  {
    name: "Taibah University",
    country: "Saudi Arabia",
    city: "Madinah",
    worldRanking: 1201,
    localRanking: 13,
    type: "public" as const,
    website: "https://www.taibahu.edu.sa",
  },
  {
    name: "Islamic University of Madinah",
    country: "Saudi Arabia",
    city: "Madinah",
    worldRanking: 1201,
    localRanking: 14,
    type: "public" as const,
    website: "https://www.iu.edu.sa",
  },
  {
    name: "Jazan University",
    country: "Saudi Arabia",
    city: "Jazan",
    worldRanking: 1401,
    localRanking: 15,
    type: "public" as const,
    website: "https://www.jazanu.edu.sa",
  },

  // QATAR
  {
    name: "Qatar University",
    country: "Qatar",
    city: "Doha",
    worldRanking: 122,
    localRanking: 1,
    type: "public" as const,
    website: "https://www.qu.edu.qa",
  },
  {
    name: "Hamad Bin Khalifa University (HBKU)",
    country: "Qatar",
    city: "Doha",
    worldRanking: 301,
    localRanking: 2,
    type: "public" as const,
    website: "https://www.hbku.edu.qa",
  },
  {
    name: "Texas A&M University at Qatar",
    country: "Qatar",
    city: "Doha",
    worldRanking: 401,
    localRanking: 3,
    type: "branch" as const,
    website: "https://www.qatar.tamu.edu",
  },
  {
    name: "Carnegie Mellon University in Qatar",
    country: "Qatar",
    city: "Doha",
    worldRanking: 401,
    localRanking: 4,
    type: "branch" as const,
    website: "https://www.qatar.cmu.edu",
  },
  {
    name: "Georgetown University in Qatar",
    country: "Qatar",
    city: "Doha",
    worldRanking: 401,
    localRanking: 5,
    type: "branch" as const,
    website: "https://qatar.georgetown.edu",
  },
  {
    name: "Weill Cornell Medicine - Qatar",
    country: "Qatar",
    city: "Doha",
    worldRanking: 401,
    localRanking: 6,
    type: "branch" as const,
    website: "https://qatar-weill.cornell.edu",
  },
  {
    name: "Northwestern University in Qatar",
    country: "Qatar",
    city: "Doha",
    worldRanking: 401,
    localRanking: 7,
    type: "branch" as const,
    website: "https://www.qatar.northwestern.edu",
  },
  {
    name: "Virginia Commonwealth University School of the Arts in Qatar",
    country: "Qatar",
    city: "Doha",
    worldRanking: 501,
    localRanking: 8,
    type: "branch" as const,
    website: "https://qatar.vcu.edu",
  },
  {
    name: "University of Doha for Science and Technology (UDST)",
    country: "Qatar",
    city: "Doha",
    worldRanking: 801,
    localRanking: 9,
    type: "public" as const,
    website: "https://www.udst.edu.qa",
  },
  {
    name: "Doha Institute for Graduate Studies",
    country: "Qatar",
    city: "Doha",
    worldRanking: 1001,
    localRanking: 10,
    type: "private" as const,
    website: "https://www.dohainstitute.edu.qa",
  },

  // BAHRAIN
  {
    name: "University of Bahrain",
    country: "Bahrain",
    city: "Sakhir",
    worldRanking: 801,
    localRanking: 1,
    type: "public" as const,
    website: "http://www.uob.edu.bh",
  },
  {
    name: "Applied Science University (ASU)",
    country: "Bahrain",
    city: "East Al-Ekir",
    worldRanking: 1001,
    localRanking: 2,
    type: "private" as const,
    website: "https://www.asu.edu.bh",
  },
  {
    name: "Ahlia University",
    country: "Bahrain",
    city: "Manama",
    worldRanking: 1001,
    localRanking: 3,
    type: "private" as const,
    website: "https://www.ahlia.edu.bh",
  },
  {
    name: "Arabian Gulf University",
    country: "Bahrain",
    city: "Manama",
    worldRanking: 1201,
    localRanking: 4,
    type: "public" as const,
    website: "https://www.agu.edu.bh",
  },
  {
    name: "Royal University for Women",
    country: "Bahrain",
    city: "Riffa",
    worldRanking: 1401,
    localRanking: 5,
    type: "private" as const,
    website: "https://www.ruw.edu.bh",
  },

  // KUWAIT
  {
    name: "Kuwait University",
    country: "Kuwait",
    city: "Kuwait City",
    worldRanking: 851,
    localRanking: 1,
    type: "public" as const,
    website: "https://www.ku.edu.kw",
  },
  {
    name: "American University of the Middle East (AUM)",
    country: "Kuwait",
    city: "Egaila",
    worldRanking: 601,
    localRanking: 2,
    type: "private" as const,
    website: "https://www.aum.edu.kw",
  },
  {
    name: "Gulf University for Science and Technology (GUST)",
    country: "Kuwait",
    city: "Mishref",
    worldRanking: 801,
    localRanking: 3,
    type: "private" as const,
    website: "https://www.gust.edu.kw",
  },
  {
    name: "American University of Kuwait (AUK)",
    country: "Kuwait",
    city: "Salmiya",
    worldRanking: 1001,
    localRanking: 4,
    type: "private" as const,
    website: "https://www.auk.edu.kw",
  }
];
