// Malaysian scholarships sourced from unienrol.com and official providers

export const MY_SCHOLARSHIPS = [
  {
    name: "Xiamen University Malaysia Merit Scholarship",
    provider: "Xiamen University Malaysia",
    providerType: "university" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["Malaysia", "All Countries"],
    deadline: new Date("2026-12-31").toISOString(),
    studyLevels: ["Foundation", "Undergraduate"],
    eligibilityCriteria: {
      level: "Foundation, Undergraduate",
      basis: "Academic merit — awarded instantly based on results",
      valueNote: "Fee waiver up to 100%",
      intake: "Open intake",
    },
    description:
      "The Xiamen University Malaysia Merit Scholarship offers a fee waiver of up to 100% to Foundation and Degree students based on academic merit. The scholarship is awarded instantly upon meeting the merit criteria at the time of application.",
    applicationUrl: "https://www.xmu.edu.my/scholarships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Xiamen University Malaysia XMUM Progression Scholarship",
    provider: "Xiamen University Malaysia",
    providerType: "university" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["Malaysia", "All Countries"],
    deadline: new Date("2026-12-31").toISOString(),
    studyLevels: ["Undergraduate"],
    eligibilityCriteria: {
      level: "Undergraduate (Degree)",
      basis: "Academic progression — awarded to existing students progressing from Foundation to Degree at XMUM",
      valueNote: "Fee waiver up to 100%",
    },
    description:
      "The XMUM Progression Scholarship is awarded to students who progress from Foundation to Degree programmes at Xiamen University Malaysia. It provides a fee waiver of up to 100% based on academic performance during the Foundation programme.",
    applicationUrl: "https://www.xmu.edu.my/scholarships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Xiamen University Malaysia International Student Scholarship",
    provider: "Xiamen University Malaysia",
    providerType: "university" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-12-31").toISOString(),
    studyLevels: ["Foundation", "Undergraduate"],
    eligibilityCriteria: {
      level: "Foundation, Undergraduate",
      feeStatus: "International students",
      valueNote: "Fee waiver up to 100%",
    },
    description:
      "The Xiamen University Malaysia International Student Scholarship offers international students a fee waiver of up to 100% for Foundation and Degree programmes. The scholarship is designed to attract global talent to study at XMUM's campus in Sepang, Selangor.",
    applicationUrl: "https://www.xmu.edu.my/scholarships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Yayasan Khazanah Global Scholarship",
    provider: "Khazanah Nasional Berhad",
    providerType: "foundation" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: [
      "Business",
      "Economics",
      "Engineering",
      "Law",
      "Social Sciences",
      "Sciences",
      "Technology",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: new Date("2026-05-31").toISOString(),
    studyLevels: ["Undergraduate"],
    eligibilityCriteria: {
      level: "Undergraduate",
      nationality: "Malaysian citizen",
      academicRequirement: "Minimum 9As in SPM or equivalent; strong co-curricular and leadership record",
      destinationUniversities: "Top universities globally (e.g. Oxford, Cambridge, Imperial, LSE, Ivy League, etc.)",
      bond: "Scholars are expected to contribute to Malaysia's development upon graduation",
      valueNote: "Full scholarship covering tuition, living allowance, travel, and other expenses",
      applicationPeriod: "Applications typically open early in the year",
    },
    description:
      "The Yayasan Khazanah Global Scholarship is a fully funded scholarship offered by Khazanah Nasional Berhad for outstanding Malaysian students to pursue undergraduate studies at top universities worldwide, including Oxford, Cambridge, Imperial College, LSE, and Ivy League institutions. It covers full tuition fees, living allowance, travel, and other related expenses. Applicants are expected to demonstrate exceptional academic achievement (minimum 9As SPM or equivalent), strong leadership qualities, and a commitment to contributing to Malaysia's national development upon graduation.",
    applicationUrl: "https://yayasankhazanah.com.my",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Yayasan UEM Global Scholarship",
    provider: "UEM Group Berhad",
    providerType: "corporate" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: [
      "Engineering",
      "Construction Management",
      "Quantity Surveying",
      "Architecture",
      "Business",
      "Finance",
      "Information Technology",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: new Date("2026-06-30").toISOString(),
    studyLevels: ["Undergraduate"],
    eligibilityCriteria: {
      level: "Undergraduate",
      nationality: "Malaysian citizen",
      academicRequirement: "Minimum 8As in SPM or equivalent A-Level / Foundation results",
      targetUniversities: "Reputable universities locally and internationally",
      bond: "Scholars may be offered employment with UEM Group upon graduation",
      valueNote: "Full scholarship — tuition fees, living allowance, and other expenses covered",
    },
    description:
      "The Yayasan UEM Global Scholarship is offered by UEM Group Berhad to outstanding Malaysian students pursuing undergraduate studies in Engineering, Construction Management, Quantity Surveying, Architecture, Business, Finance, or Information Technology at reputable universities locally or internationally. The full scholarship covers tuition fees, living allowance, and other expenses. Scholars may be offered placement within the UEM Group upon graduation.",
    applicationUrl: "https://www.uem.com.my/scholarships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "PETRONAS Education Sponsorship Programme (PESP)",
    provider: "PETRONAS",
    providerType: "corporate" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: [
      "Engineering",
      "Chemical Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Civil Engineering",
      "Geoscience",
      "Petroleum Engineering",
      "Information Technology",
      "Business",
      "Finance",
      "Accounting",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: new Date("2026-06-30").toISOString(),
    studyLevels: ["Undergraduate", "Postgraduate"],
    eligibilityCriteria: {
      level: "Undergraduate (local & overseas) and Postgraduate",
      nationality: "Malaysian citizen",
      academicRequirement: "Minimum 8As in SPM or equivalent; strong CGPA for postgraduate",
      sponsorshipPeriod: "Duration of the programme",
      bond: "Work bond with PETRONAS upon graduation",
      valueNote: "Full sponsorship — tuition, living allowance, book allowance, medical, and other benefits",
      employmentNote: "PESP scholars are expected to join PETRONAS and its subsidiaries upon graduation",
    },
    description:
      "The PETRONAS Education Sponsorship Programme (PESP) is a full sponsorship offered by PETRONAS to outstanding Malaysian students for undergraduate and postgraduate studies in STEM, Business, and Finance disciplines at local and overseas universities. Benefits include full tuition coverage, monthly living allowance, book allowance, medical coverage, and a return flight ticket. Scholars are bonded to join PETRONAS or its subsidiaries upon graduation. Applicants must be Malaysian citizens with a strong academic track record (minimum 8As SPM or equivalent).",
    applicationUrl: "https://www.petronas.com/sustainability/education/scholarship",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "CIMB ASEAN Scholarship",
    provider: "CIMB Bank",
    providerType: "corporate" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: [
      "Business",
      "Finance",
      "Economics",
      "Accounting",
      "Engineering",
      "Information Technology",
      "Law",
    ],
    eligibleCountries: ["Malaysia", "Indonesia", "Thailand", "Singapore", "Cambodia", "Philippines", "Vietnam"],
    deadline: new Date("2026-06-30").toISOString(),
    studyLevels: ["Undergraduate"],
    eligibilityCriteria: {
      level: "Undergraduate",
      nationality: "Citizens of ASEAN countries where CIMB operates",
      academicRequirement: "Exceptional academic results; strong leadership and co-curricular record",
      targetUniversities: "Top universities globally",
      valueNote: "Full scholarship covering tuition, living allowance, and related expenses",
      bond: "Scholars are expected to join CIMB Group upon graduation",
      contact: "scholarships@cimb.com",
    },
    description:
      "The CIMB ASEAN Scholarship is a fully funded scholarship for outstanding students from ASEAN countries to study at top universities globally. Open to citizens of Malaysia, Indonesia, Thailand, Singapore, Cambodia, Philippines, and Vietnam, the scholarship covers tuition fees, living allowance, and related expenses. Eligible fields include Business, Finance, Economics, Accounting, Engineering, IT, and Law. Scholars are expected to join CIMB Group upon completing their studies.",
    applicationUrl: "https://www.cimb.com/en/who-we-are/cimb-foundation/scholarships.html",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Bank Negara Malaysia Kijang Pre-University Scholarship",
    provider: "Bank Negara Malaysia (BNM)",
    providerType: "government" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: [
      "Economics",
      "Finance",
      "Business",
      "Accounting",
      "Actuarial Science",
      "Statistics",
      "Mathematics",
      "Engineering",
      "Law",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: new Date("2026-05-31").toISOString(),
    studyLevels: ["Undergraduate"],
    eligibilityCriteria: {
      level: "Undergraduate (via Pre-University / A-Level / Foundation pathway)",
      nationality: "Malaysian citizen",
      academicRequirement: "Minimum 9As in SPM including Mathematics and English; strong leadership qualities",
      preUniversityPath: "Scholars complete a pre-university programme (A-Levels / Foundation) before proceeding to a top university",
      targetUniversities: "Top universities globally (UK, USA, Australia, etc.)",
      valueNote: "Full scholarship — pre-university fees, degree tuition, living allowance, travel, and other benefits",
      bond: "Scholars join Bank Negara Malaysia upon graduation",
    },
    description:
      "The Bank Negara Malaysia (BNM) Kijang Pre-University Scholarship is a fully funded scholarship for top SPM graduates to pursue pre-university studies followed by a degree at a leading university worldwide. The scholarship covers all pre-university fees, degree tuition, monthly living allowance, travel expenses, and other associated costs. Eligible fields include Economics, Finance, Business, Actuarial Science, Engineering, Mathematics, and Law. Scholars are bonded to serve Bank Negara Malaysia upon graduation. Applicants must be Malaysian citizens with a minimum of 9As in SPM including Mathematics and English.",
    applicationUrl: "https://www.bnm.gov.my/scholarship",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "JPA Scholarship – Program Penajaan Nasional (PPN)",
    provider: "Jabatan Perkhidmatan Awam (JPA) Malaysia",
    providerType: "government" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: [
      "Medicine",
      "Dentistry",
      "Pharmacy",
      "Engineering",
      "Architecture",
      "Law",
      "Accounting",
      "Islamic Studies",
      "Education",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: new Date("2026-06-30").toISOString(),
    studyLevels: ["Undergraduate"],
    eligibilityCriteria: {
      level: "Undergraduate",
      nationality: "Malaysian citizen",
      academicRequirement: "Excellent SPM results; income-based eligibility for certain categories",
      programmeTypes: "Local universities (IPTA) and selected private institutions (IPTS)",
      loanConversion: "Convertible loan — converts to scholarship upon achieving minimum CGPA",
      valueNote: "Full sponsorship — tuition fees, living allowance, and related costs",
      contact: "03-8000 8000 | ppninfo@jpa.gov.my",
    },
    description:
      "The JPA Program Penajaan Nasional (PPN) is a sponsorship scheme by Malaysia's Public Service Department (JPA) for outstanding Malaysians to pursue undergraduate studies at local public universities (IPTA) and selected private institutions. Eligible fields include Medicine, Dentistry, Pharmacy, Engineering, Architecture, Law, and Accounting. The sponsorship is initially a convertible loan — it converts to a full scholarship upon maintaining the minimum required CGPA throughout the programme. Benefits include full tuition fees and a monthly living allowance.",
    applicationUrl: "https://www.jpa.gov.my/scholarship",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "MARA Scholarship – Program Khas JPA-MARA (PKJM)",
    provider: "Majlis Amanah Rakyat (MARA)",
    providerType: "government" as const,
    value: 0,
    currency: "MYR",
    eligibleFields: [
      "Engineering",
      "Medicine",
      "Dentistry",
      "Pharmacy",
      "Architecture",
      "Law",
      "Accounting",
      "Business",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: new Date("2026-04-30").toISOString(),
    studyLevels: ["Undergraduate"],
    eligibilityCriteria: {
      level: "Undergraduate",
      nationality: "Malaysian Bumiputera citizen",
      academicRequirement: "Excellent SPM 2025 results; first-time SPM candidate",
      targetUniversities: "Selected overseas universities (UK, Australia, Ireland, etc.)",
      note: "Applicants may only choose ONE programme — PKJM or JKPJ 2026",
      valueNote: "Full scholarship covering tuition, living allowance, travel, and other expenses",
      contact: "03-2613 2000",
    },
    description:
      "The MARA Program Khas JPA-MARA (PKJM) is a fully funded scholarship for outstanding Bumiputera SPM graduates to pursue undergraduate studies at selected overseas universities in the UK, Australia, Ireland, and other countries. Eligible fields include Engineering, Medicine, Dentistry, Pharmacy, Architecture, Law, Accounting, and Business. The scholarship covers tuition, monthly living allowance, travel, and related expenses. Note: applicants may only apply for ONE programme — either PKJM or the JPA Program Khas JKPJ 2026.",
    applicationUrl: "https://www.mara.gov.my/scholarship",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
