// SPM 2025 - Top 25 Prestigious Malaysian Scholarships
// Scraped and compiled from official scholarship portals (March 2026)
// Note: Excludes scholarships already in seedDataScraped.ts:
//   Bank Negara Malaysia, Shell Malaysia, Telekom Malaysia, Tenaga Nasional,
//   Khazanah, Yayasan Tunku Abdul Rahman, Maybank/CIMB/RHB (Financial Institutions)

export const spm2025Scholarships = [
  {
    name: "JPA Scholarship (Program Penajaan Nasional)",
    provider: "Jabatan Perkhidmatan Awam (JPA)",
    providerType: "government" as const,
    value: 60000,
    currency: "MYR",
    eligibleFields: [
      "Engineering",
      "Medicine",
      "Law",
      "Accounting",
      "Science",
      "Technology",
      "All Fields",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-05-31T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen. Excellent SPM results (typically 8A+ and above). Strong co-curricular record. Household income criteria may apply for certain programmes (B40/M40). Programmes include overseas (LSPM) and local (PIDN) sponsorships.",
      timePeriod: "7–21 days after SPM results are released (typically March–April)",
    },
    description:
      "Malaysia's most prestigious government scholarship, offered by the Public Service Department (JPA). Covers tuition fees, living allowance, accommodation, airfare, and insurance for top SPM leavers to study locally or at leading universities worldwide. Multiple programmes available including Program Penajaan Nasional (PPN) for overseas and Program Ijazah Dalam Negara (PIDN) for local studies.",
    applicationUrl: "https://esilav2.jpa.gov.my",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "MARA Scholarship (YTP / TESP)",
    provider: "Majlis Amanah Rakyat (MARA)",
    providerType: "government" as const,
    value: 55000,
    currency: "MYR",
    eligibleFields: [
      "Engineering",
      "Medicine",
      "Dentistry",
      "Pharmacy",
      "Science",
      "Technology",
      "Business",
      "Architecture",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-05-31T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian Bumiputera citizen. Excellent SPM results. Good conduct and active co-curricular participation. Programmes include Yayasan Tajaan Pelajaran (YTP) for outstanding students and Twinning Education Sponsorship Programme (TESP). Must not be holding any other scholarship.",
      timePeriod: "7–21 days after SPM results are released (typically March–April)",
    },
    description:
      "One of Malaysia's largest scholarship providers for Bumiputera students, MARA offers sponsorships for pre-university and undergraduate studies both locally and at premier universities abroad (UK, US, Australia, Middle East). Benefits include full tuition, monthly allowance, accommodation, airfare, and book allowance.",
    applicationUrl: "https://educationloan.mara.gov.my/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "PETRONAS Education Sponsorship Programme (PESP)",
    provider: "PETRONAS",
    providerType: "corporate" as const,
    value: 70000,
    currency: "MYR",
    eligibleFields: [
      "Engineering",
      "Petroleum Sciences",
      "Business",
      "Law",
      "Information Technology",
      "Science",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-04-10T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen. Local (UTP): Minimum 8A in SPM + CEFR B1. Overseas: Minimum 4A+ and 4A in SPM + CEFR C1. Strong leadership qualities and co-curricular achievement. Must not exceed age limit. Bond obligation to PETRONAS upon graduation.",
      timePeriod: "31 March – 10 April 2026 (currently open for 2026 intake)",
    },
    description:
      "PETRONAS offers sponsorships for SPM leavers to pursue studies at Universiti Teknologi PETRONAS (UTP) and leading overseas universities in the US, UK, Australia, New Zealand, China, Japan, and South Korea. Covers full tuition, monthly allowance, accommodation, books, laptop, and travel. One of Malaysia's most competitive and comprehensive corporate scholarships.",
    applicationUrl: "https://www.petronas.com/careers/students-graduates",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Bank Pembangunan Malaysia Berhad Scholarship (BAGUS)",
    provider: "Bank Pembangunan Malaysia Berhad (BPMB)",
    providerType: "corporate" as const,
    value: 30000,
    currency: "MYR",
    eligibleFields: [
      "Finance",
      "Economics",
      "Business",
      "Engineering",
      "Information Technology",
      "All Fields",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen. Excellent academic results. Strong co-curricular involvement. Financial need may be considered. Bond obligation upon graduation.",
      timePeriod: "Typically opens after SPM results; check BPMB website for exact dates",
    },
    description:
      "The BAGUS (Bank Pembangunan Graduan Unggul Strategik) Scholarship is offered by Bank Pembangunan Malaysia Berhad to empower deserving Malaysian students with financial support to pursue higher education at recognized institutions. Covers tuition fees, monthly allowance, and other educational expenses.",
    applicationUrl: "https://www.bpmb.com.my/scholarship/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Yayasan Sime Darby Scholarship",
    provider: "Yayasan Sime Darby",
    providerType: "foundation" as const,
    value: 20000,
    currency: "MYR",
    eligibleFields: [
      "Business",
      "Engineering",
      "Architecture",
      "Built Environment",
      "All Fields",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen aged 25 or below. Undergraduate Excellence Scholarship: Minimum CGPA 3.30 from pre-university; household income RM 11,000/month or below; leadership experience required; studying at one of 10 approved Malaysian institutions. Special Needs Bursary: Registered OKU cardholder; minimum CGPA 2.50; all fields except Medicine.",
      timePeriod: "Applications currently open; check YSD website for closing date",
    },
    description:
      "Yayasan Sime Darby offers multiple scholarship and bursary programmes. The YSD Undergraduate Excellence Scholarship supports outstanding Malaysian undergraduates in Business, Engineering, and Architecture. The YSD Special Needs Bursary provides up to RM 15,000/year for students with disabilities. TVET sponsorships are also available for Plantation, Heavy Equipment, and Construction fields.",
    applicationUrl: "https://www.yayasansimedarby.com/scholarship-information",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Yayasan UEM Global Scholarship",
    provider: "Yayasan UEM",
    providerType: "foundation" as const,
    value: 40000,
    currency: "MYR",
    eligibleFields: [
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Business",
      "Accounting",
      "Finance",
      "Information Technology",
      "Environmental Studies",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-04-12T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen. Global Scholarship: Minimum 7 A's in SPM; strong English proficiency; leadership and co-curricular achievements. Wira Scholarship: Minimum CGPA 3.5 at pre-university level. Willing to serve UEM Group upon graduation.",
      timePeriod: "Deadline: April 12, 2026",
    },
    description:
      "Yayasan UEM offers the Undergraduate Global Scholarship and Wira Scholarship for Malaysian SPM leavers and pre-university students. Global scholars study pre-university at KYUEM before proceeding to top global universities. Coverage includes full tuition, fees, insurance, laptop, study materials, and subsistence allowance. A Graduate Accounting Programme is also available for accounting studies in the UK or Australia.",
    applicationUrl: "https://www.uem.com.my/yayasan-scholarship",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Yayasan Bank Rakyat Education Financing (PPBU)",
    provider: "Yayasan Bank Rakyat",
    providerType: "foundation" as const,
    value: 20000,
    currency: "MYR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen. Secured admission to a Diploma or Bachelor's Degree programme at a recognized public or private institution. Good academic standing.",
      timePeriod: "Open intake; check Yayasan Bank Rakyat portal for current availability",
    },
    description:
      "Yayasan Bank Rakyat offers the Pembiayaan Pendidikan Boleh Ubah (PPBU) programme, providing financial assistance to qualified Malaysian students pursuing Diploma or Bachelor's Degree programmes at recognized institutions. The programme aims to support the socioeconomic development of Malaysians through accessible higher education financing.",
    applicationUrl: "https://www.yayasanbankrakyat.com.my/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Yayasan Peneraju Scholarship",
    provider: "Yayasan Peneraju Pendidikan Bumiputera",
    providerType: "foundation" as const,
    value: 15000,
    currency: "MYR",
    eligibleFields: [
      "Vocational & Technical",
      "Professional Certification",
      "Technology",
      "Healthcare",
      "Oil & Gas",
      "Accounting",
      "Finance",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Bumiputera Malaysian. Peneraju Tunas targets M40 and below family income groups. Various programmes cater to different education levels, from certification to professional development. Check individual programme requirements on the Yayasan Peneraju portal.",
      timePeriod: "Applications opened January 5, 2026; rolling intake for some programmes",
    },
    description:
      "Yayasan Peneraju Pendidikan Bumiputera provides financing for critical skills development and industry-recognized certifications. Programmes include Peneraju Tunas (certification), Peneraju Skil (vocational/technical), Pensijilan Profesional (accounting & finance), Pensijilan Teknologi (Big Data, Cybersecurity, AI, Cloud), and Peneraju Spesialis (healthcare). Focuses on Bumiputera workforce upskilling.",
    applicationUrl: "https://yayasanpeneraju.com.my/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "CIMB ASEAN Scholarship",
    provider: "CIMB Bank",
    providerType: "corporate" as const,
    value: 60000,
    currency: "MYR",
    eligibleFields: [
      "Business",
      "Marketing",
      "Economics",
      "Finance",
      "Science",
      "Engineering",
      "Social Sciences",
      "Data Science",
    ],
    eligibleCountries: ["Malaysia", "Indonesia", "Singapore", "Thailand", "Vietnam"],
    deadline: "2026-04-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Age 25 or below. Citizen of Malaysia, Indonesia, Singapore, Thailand, or Vietnam. Strong academic record (Malaysia: majority A's in SPM / 3 A's in STPM / 37 IB points). Aspiring to build a career in banking and financial services. Currently in pre-university/diploma or starting undergraduate year. Must not hold other contractual scholarships.",
      timePeriod: "April 2026",
    },
    description:
      "The CIMB ASEAN Scholarship is a prestigious full scholarship open to top students across 5 ASEAN countries. It covers full tuition fees, laptop, books, visa, airfare, and living allowances. Scholars receive mentorship, internship opportunities at CIMB Group, and guaranteed employment upon graduation — making it one of the most holistic scholarship packages in Southeast Asia.",
    applicationUrl: "https://www.cimb.com/en/careers/students/cimb-asean-scholarship.html",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Public Bank Scholarship (Tan Sri Teh Hong Piow)",
    provider: "Public Bank Berhad",
    providerType: "corporate" as const,
    value: 30000,
    currency: "MYR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen aged 18–25. Minimum 5 A's in SPM or equivalent. Minimum CGPA 3.50 in STPM/Foundation/Matriculation/Diploma. Pursuing first-year full-time undergraduate at a recognized Malaysian university. Cannot receive other financial assistance including PTPTN. Must commit to employment bond with Public Bank Group upon graduation.",
      timePeriod: "Typically opens mid-year; verify current deadline on Public Bank website",
    },
    description:
      "Named after the founder of Public Bank, the Tan Sri Teh Hong Piow Scholarship supports deserving Malaysian students demonstrating exceptional academic achievement, strong leadership, and active co-curricular involvement. It is a bonded scholarship requiring commitment to work with Public Bank Group after graduation.",
    applicationUrl: "https://www.publicbankgroup.com/careers/public-bank-berhad-scholarship/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Hong Leong Foundation Scholarship",
    provider: "Hong Leong Foundation",
    providerType: "foundation" as const,
    value: 20000,
    currency: "MYR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-05-31T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen aged 17–25. Completed SPM/STPM/UEC. Total monthly household income ≤ RM 5,000. Currently enrolled in or accepted to a Diploma, Advanced Diploma, or first-degree programme at a recognized Malaysian institution. Non-bonding scholarship.",
      timePeriod: "April 1 – May 31 annually",
    },
    description:
      "The Hong Leong Foundation Scholarship provides financial support for Malaysian students at Diploma and Undergraduate levels at recognized local institutions. Awards range from RM 6,000/year (public university) to RM 32,000/year (Medicine/Dentistry at private university). Targeted at students from lower-income households (monthly income ≤ RM 5,000). Non-bonding — no work obligation required.",
    applicationUrl: "https://www.hongleongfoundation.com/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Yayasan IOI Bachelor Degree Scholarship",
    provider: "IOI Group",
    providerType: "foundation" as const,
    value: 35000,
    currency: "MYR",
    eligibleFields: [
      "Engineering",
      "Food Science",
      "Food Technology",
      "Chemistry",
      "Risk Management",
      "Accountancy",
      "Finance",
      "Data Science",
      "Agriculture",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "First or second-year undergraduates with CGPA ≥ 3.3 or Upper Second-Class Honours equivalent. Outstanding co-curricular achievements and leadership qualities. Not currently receiving other scholarships. Must commit to post-graduation employment bond with IOI Group.",
      timePeriod: "Check Yayasan IOI website for current intake dates",
    },
    description:
      "Yayasan IOI offers a Bachelor Degree Scholarship for high-achieving undergraduates in select fields aligned with IOI Group's business interests, including Engineering, Food Science, Data Science, and Agriculture. Benefits include full tuition fees at approved Malaysian universities and a monthly living allowance. Comes with an employment bond obligation with IOI Group upon graduation.",
    applicationUrl: "https://yayasan.ioigroup.com/initiative-programs/scholarships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Sunway Group Scholarship",
    provider: "Sunway Group / Jeffrey Cheah Foundation",
    providerType: "foundation" as const,
    value: 25000,
    currency: "MYR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["Malaysia", "International"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Strong academic performance (GPA varies by programme). Chancellor's Scholarship: Highest academic achievers. Community Scholarship: Demonstrated financial need + academic merit. Sports Scholarship: National or varsity-level athletic achievement. Leadership Scholarship: Outstanding academic and extracurricular record.",
      timePeriod: "Check Sunway scholarship portal for specific programme deadlines",
    },
    description:
      "Sunway Group, through the Jeffrey Cheah Foundation, has awarded over RM 967 million in scholarships to thousands of students. Programmes include the Chancellor's Scholarship (Sunway University & Lancaster University partnership), the Sunway Entrance Scholarship, the Jeffrey Cheah Foundation Community Scholarship, and Sports Scholarships. Covers tuition fees partially or in full depending on the award.",
    applicationUrl: "https://scholarship.sunway.edu.my/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Yayasan Gamuda Scholarship",
    provider: "Yayasan Gamuda",
    providerType: "foundation" as const,
    value: 45000,
    currency: "MYR",
    eligibleFields: [
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Built Environment",
      "Construction Management",
      "Quantity Surveying",
      "Property & Real Estate",
      "Technology & Digital",
      "Business & Finance",
      "Sustainability",
      "Psychology",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian IC holder. Minimum 3 A's or CGPA 3.40 in STPM/A-Levels/Matriculation/Foundation/Diploma/UEC. Good English communication. Pre-university leaver or first-degree student (Year 1–3). Strong leadership qualities and community service record. Evidence of financial need. Must not be receiving other scholarships. Bond obligation to serve Gamuda Group post-graduation.",
      timePeriod: "2025 intake open; check Yayasan Gamuda website for closing date",
    },
    description:
      "Yayasan Gamuda has supported over 763 students since 1996. The scholarship covers comprehensive expenses including tuition fees, monthly living allowance, accommodation, books, laptop, and airfare for overseas studies. Scholars also benefit from leadership training and career development programmes within Gamuda Group. Covers a wide range of fields aligned with Gamuda's infrastructure, technology, and business interests.",
    applicationUrl: "https://gamuda.com/yayasan-gamuda/scholarship/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Axiata Foundation Scholarship",
    provider: "Axiata Foundation",
    providerType: "foundation" as const,
    value: 30000,
    currency: "MYR",
    eligibleFields: [
      "Digital Technology",
      "Data Science",
      "Cybersecurity",
      "Engineering",
      "Business",
      "All Fields",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "All-Star Bestari (AEiEF): Minimum 6 A's in SPM (A+, A, or A-); from low-income, underprivileged backgrounds or marginalized communities. Axiata Young Talent Programme (AYTP): Varies; leadership development focus. Digital Leaders Programme (ADLP): Varies.",
      timePeriod: "Deadlines vary by programme; previously noted June 30 — verify on Axiata Foundation website",
    },
    description:
      "Axiata Foundation runs multiple scholarship and talent development programmes to promote equitable access to quality education across Malaysia. The All-Star Bestari Scholarship (under the Axiata Equity in Education Fund) targets high-achieving SPM students from underprivileged backgrounds. The Axiata Young Talent Programme and Digital Leaders Programme focus on developing future leaders in the digital economy. Benefits include full education and living expense coverage.",
    applicationUrl: "https://www.axiata-foundation.com/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Sarawak Energy Scholarship",
    provider: "Sarawak Energy",
    providerType: "corporate" as const,
    value: 40000,
    currency: "MYR",
    eligibleFields: [
      "Engineering",
      "Science",
      "Technology",
      "Business",
      "Finance",
      "Information Technology",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-06-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen, preference for Sarawakians. Excellent academic record. Strong co-curricular involvement. Bond obligation to Sarawak Energy upon graduation. Specific requirements available on Sarawak Energy careers portal.",
      timePeriod: "Check Sarawak Energy website for current intake dates",
    },
    description:
      "Sarawak Energy offers scholarships for promising Malaysian students, with a preference for Sarawakians, to pursue undergraduate studies in Engineering, Science, Technology, Business, and related fields. The programme aims to build a skilled local talent pipeline for Sarawak's growing energy sector. Covers tuition fees, monthly allowance, and other educational expenses.",
    applicationUrl: "https://www.sarawakenergy.com/careers/scholarship",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "MNRB Scholarship Fund",
    provider: "MNRB (Malaysian National Reinsurance Berhad)",
    providerType: "corporate" as const,
    value: 30000,
    currency: "MYR",
    eligibleFields: [
      "Insurance & Risk Management",
      "Data Science",
      "Artificial Intelligence",
      "Geology",
      "Environmental Science",
      "Accounting",
      "Mathematics",
      "Statistics",
      "Actuarial Science",
      "Civil Engineering",
      "Law",
      "Economics",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-04-15T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen. Foundation Studies: Minimum 7 A's in SPM (including Mathematics) + CEFR B1; not exceeding 18 years at enrolment. Undergraduate: Same academic standards; age 23 or below at application. Trial SPM results are acceptable. Bond obligation upon graduation.",
      timePeriod: "Opens January 30, 2026; closes approximately two weeks after SPM 2025 results release",
    },
    description:
      "Established on April 1, 1998, the MNRB Scholarship Fund has supported over 700 Malaysian students in developing the country's insurance and takaful industries. The fund covers Foundation Studies and Undergraduate programmes in fields like Actuarial Science, Data Science, Risk Management, and Law. MNRB has been a key contributor to building professional talent in Malaysia's reinsurance sector.",
    applicationUrl: "https://www.mnrb.com.my/careers/scholarships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "YTL Foundation Scholarship Programme",
    provider: "YTL Foundation",
    providerType: "foundation" as const,
    value: 40000,
    currency: "MYR",
    eligibleFields: [
      "Civil Engineering",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Quantity Surveying",
      "Construction Project Management",
      "Finance",
      "Business",
      "Creative Arts",
      "Accounting",
      "Computer Science",
      "Social Sciences",
    ],
    eligibleCountries: ["Malaysia"],
    deadline: "2026-04-30T23:59:59.000Z",
    eligibilityCriteria: {
      requirements:
        "Malaysian citizen. YTL Foundation Scholarship: SPM minimum 7 A's / STPM minimum CGPA 3.50 / Matriculation or Foundation minimum CGPA 3.70 / A-Levels minimum 2 A's / IB minimum 37 points / AUSMAT minimum ATAR 75. Must come from a family that finds it challenging to finance education. Yeoh Tiong Lay Award (premium): Higher thresholds — SPM minimum 8 A's / IB minimum 40 points. Bond: 5–7 years with YTL Group.",
      timePeriod: "Deadline: April 30 annually",
    },
    description:
      "YTL Foundation offers up to 30 scholarships annually through two programmes. The YTL Foundation Scholarship covers full tuition, living expenses, laptop, phone/data plan, paid internships, and development programmes, with possible employment at YTL Group. The premium Yeoh Tiong Lay Award provides one overseas undergraduate seat annually at a top global university, including full coverage, annual return flights, UK development programme, and individual coaching. Both target students with financial need.",
    applicationUrl: "https://ytlfoundation.org/applynow/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
