// Seed data for scholarships - subset of mock data for initial population
export const seedScholarships = [
  {
    name: 'ASEAN Undergraduate Scholarship',
    provider: 'Singapore Ministry of Education',
    providerType: 'government' as const,
    value: 25000,
    currency: 'SGD',
    eligibleFields: ['Engineering', 'Computer Science', 'Business Administration'],
    eligibleCountries: ['Singapore', 'Malaysia', 'Indonesia', 'Thailand', 'Vietnam', 'Philippines'],
    deadline: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      minGPA: 3.5,
      ageLimit: 25,
      languageRequirement: 'English',
    },
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Chevening Scholarship',
    provider: 'UK Government',
    providerType: 'government' as const,
    value: 50000,
    currency: 'GBP',
    eligibleFields: ['All Fields'],
    eligibleCountries: ['United Kingdom'],
    deadline: new Date(Date.now() + 210 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      workExperience: '2 years minimum',
      languageRequirement: 'English (IELTS 6.5)',
    },
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Fulbright Foreign Student Program',
    provider: 'US Department of State',
    providerType: 'government' as const,
    value: 45000,
    currency: 'USD',
    eligibleFields: ['All Fields'],
    eligibleCountries: ['United States'],
    deadline: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      degree: "Bachelor's degree",
      languageRequirement: 'English (TOEFL 90+)',
    },
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Australia Awards Scholarship',
    provider: 'Australian Government',
    providerType: 'government' as const,
    value: 40000,
    currency: 'AUD',
    eligibleFields: ['Engineering', 'Agriculture', 'Environmental Science'],
    eligibleCountries: ['Australia'],
    deadline: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      minGPA: 3.0,
      languageRequirement: 'English (IELTS 6.5)',
    },
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'DAAD Scholarship',
    provider: 'German Academic Exchange Service',
    providerType: 'government' as const,
    value: 35000,
    currency: 'EUR',
    eligibleFields: ['Engineering', 'Science', 'Arts & Humanities'],
    eligibleCountries: ['Germany'],
    deadline: new Date(Date.now() + 195 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      degree: "Bachelor's degree",
      languageRequirement: 'English or German',
    },
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
