// Seed data for scholarships - subset of mock data for initial population
export const seedScholarships = [
  {
    name: 'ASEAN Undergraduate Scholarship',
    provider: 'Singapore Ministry of Education',
    providerType: 'government' as const,
    value: 25000,
    currency: 'SGD',
    eligibleFields: ['Engineering', 'Computer Science', 'Business Administration'],
    eligibleCountries: ['Singapore', 'Malaysia', 'Indonesia', 'Thailand', 'Vietnam', 'Philippines'],
    deadline: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      minGPA: 3.5,
      ageLimit: 25,
      languageRequirement: 'English',
    },
    description: 'The ASEAN Undergraduate Scholarship is offered by the Singapore Ministry of Education to outstanding students from ASEAN member countries. This prestigious scholarship covers tuition fees, living allowance, and return airfare for the duration of the undergraduate programme at any of Singapore\'s top universities including NUS, NTU, and SMU. Recipients are expected to work in Singapore for 3 years after graduation.',
    applicationUrl: 'https://www.moe.gov.sg/financial-matters/awards-scholarships/asean-scholarships',
    applicationCount: 187,
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Chevening Scholarship',
    provider: 'UK Government',
    providerType: 'government' as const,
    value: 50000,
    currency: 'GBP',
    eligibleFields: ['All Fields'],
    eligibleCountries: ['United Kingdom'],
    deadline: new Date(Date.now() + 210 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      workExperience: '2 years minimum',
      languageRequirement: 'English (IELTS 6.5)',
    },
    description: 'Chevening Scholarships are the UK Government\'s global scholarship programme, funded by the Foreign, Commonwealth and Development Office. The scholarship covers university tuition fees, a monthly living allowance, return economy flights, and additional grants. It is aimed at developing global leaders who will return to their home countries and create positive change.',
    applicationUrl: 'https://www.chevening.org/scholarships',
    applicationCount: 243,
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Fulbright Foreign Student Program',
    provider: 'US Department of State',
    providerType: 'government' as const,
    value: 45000,
    currency: 'USD',
    eligibleFields: ['All Fields'],
    eligibleCountries: ['United States'],
    deadline: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      degree: "Bachelor's degree",
      languageRequirement: 'English (TOEFL 90+)',
    },
    description: 'The Fulbright Foreign Student Program enables graduate students, young professionals, and artists from abroad to study and conduct research in the United States. The programme covers tuition, airfare, a living stipend, and health insurance. Fulbright alumni have become heads of state, Nobel Laureates, and leaders across many fields.',
    applicationUrl: 'https://foreign.fulbrightonline.org',
    applicationCount: 156,
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Australia Awards Scholarship',
    provider: 'Australian Government',
    providerType: 'government' as const,
    value: 40000,
    currency: 'AUD',
    eligibleFields: ['Engineering', 'Agriculture', 'Environmental Science'],
    eligibleCountries: ['Australia'],
    deadline: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      minGPA: 3.0,
      languageRequirement: 'English (IELTS 6.5)',
    },
    description: 'Australia Awards Scholarships are long-term awards administered by the Department of Foreign Affairs and Trade. They aim to contribute to the development needs of Australia\'s partner countries in line with bilateral and regional agreements. The scholarships provide full tuition fees, return air travel, establishment allowance, and a contribution to living expenses.',
    applicationUrl: 'https://www.dfat.gov.au/people-to-people/australia-awards',
    applicationCount: 89,
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'DAAD Scholarship',
    provider: 'German Academic Exchange Service',
    providerType: 'government' as const,
    value: 35000,
    currency: 'EUR',
    eligibleFields: ['Engineering', 'Science', 'Arts & Humanities'],
    eligibleCountries: ['Germany'],
    deadline: new Date(Date.now() + 195 * 24 * 60 * 60 * 1000).toISOString(),
    eligibilityCriteria: {
      degree: "Bachelor's degree",
      languageRequirement: 'English or German',
    },
    description: 'The DAAD (German Academic Exchange Service) Scholarship supports international students pursuing Master\'s or PhD programmes at German universities. Benefits include a monthly stipend, health insurance, travel allowance, and study/research grants. Germany offers world-class education with many programmes taught in English, making it an attractive destination for international students.',
    applicationUrl: 'https://www.daad.de/en/study-and-research-in-germany/scholarships',
    applicationCount: 124,
    status: 'active' as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
