// Major international scholarships from government programs worldwide

export const GLOBAL_SCHOLARSHIPS = [
  {
    name: "Fulbright Foreign Student Program",
    provider: "U.S. Department of State / Institute of International Education (IIE)",
    providerType: "government" as const,
    value: 0,
    currency: "USD",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-10-31").toISOString(),
    studyLevels: ["Postgraduate", "PhD"],
    eligibilityCriteria: {
      level: "Master's degree, some PhD programs",
      academicRequirement: "Bachelor's degree or equivalent with good academic record",
      englishRequirement: "TOEFL 550 (PBT) / 79-80 (iBT) or IELTS 6.5",
      residency: "Must reside in home country at time of application",
      deadlineNote: "Country-specific deadlines typically January–October",
      coverage: "Full tuition + monthly stipend + airfare + health insurance + textbook allowance + enrichment programs",
      annualAwards: "Approximately 4,000 scholarships annually",
      contact: "Apply through country's Fulbright Commission or U.S. Embassy",
    },
    description:
      "The Fulbright Foreign Student Program enables graduate students, young professionals, and artists from 160+ countries to study and conduct research in the United States. It provides full tuition, monthly living stipend, round-trip international airfare, health insurance, textbook allowance, settlement allowance, and access to enrichment programs. Applicants must hold a bachelor's degree, have a good academic record, demonstrate English proficiency (TOEFL 79-80 or IELTS 6.5), and reside in their home country at the time of application. Approximately 4,000 scholarships are awarded annually through country-specific Fulbright Commissions or U.S. Embassies.",
    applicationUrl: "https://foreign.fulbrightonline.org/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Erasmus Mundus Joint Masters (EMJM)",
    provider: "European Commission / European Education and Culture Executive Agency (EACEA)",
    providerType: "government" as const,
    value: 33600,
    currency: "EUR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2027-01-31").toISOString(),
    studyLevels: ["Postgraduate"],
    eligibilityCriteria: {
      level: "Master's degree (1-2 years, 60-120 ECTS)",
      academicRequirement: "Bachelor's degree (180 ECTS minimum) or equivalent; in final year acceptable if graduating before program starts",
      englishRequirement: "IELTS Academic or TOEFL-iBT (some accept Duolingo, PTE)",
      residency: "Must not be resident in EU for more than 12 months in previous 5 years",
      coverage: "Full tuition + €1,400/month stipend (€33,600 over 2 years) + health insurance + travel costs",
      programStructure: "Study in 2-3 different European countries",
      deadlineNote: "Applications typically October–January for September start",
    },
    description:
      "Erasmus Mundus Joint Masters (EMJM) are high-level integrated study programs delivered by international partnerships of higher education institutions across 2-3 different European countries. Scholarships cover full tuition fees, a monthly stipend of €1,400 (totaling €33,600 over 2 years), health insurance, and travel costs. Applicants must hold a bachelor's degree (180 ECTS minimum) or be in their final year, demonstrate English proficiency, and not have been resident in the EU for more than 12 months in the previous 5 years. Programs last 1-2 years (60-120 ECTS) and offer joint or multiple degrees.",
    applicationUrl: "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "DAAD Study Scholarships for Master's Degree Programs",
    provider: "DAAD (German Academic Exchange Service)",
    providerType: "government" as const,
    value: 992,
    currency: "EUR",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-10-31").toISOString(),
    studyLevels: ["Postgraduate"],
    eligibilityCriteria: {
      level: "Master's degree",
      academicRequirement: "Bachelor's degree with above-average grades (GPA 3.0/4.0 minimum; competitive applicants: 3.5+)",
      yearsRequirement: "Not more than 6 years since last degree",
      residency: "Not resident in Germany for more than 15 months",
      languageRequirement: "English (IELTS 6.0+) or German (TestDaF/DSH)",
      coverage: "€992/month stipend + tuition fees (if applicable) + travel + health/accident/liability insurance + study/research allowances + German language course subsidies",
      annualAwards: "Approximately 100,000 scholarships across all DAAD programs",
    },
    description:
      "DAAD Study Scholarships for Master's Degree Programs support international students pursuing master's degrees at German universities in any field. Scholarships provide a monthly stipend of €992, tuition coverage (if applicable), travel allowances, health/accident/personal liability insurance, study and research allowances, and German language course subsidies. Applicants must hold a bachelor's degree with above-average grades (minimum GPA 3.0/4.0; competitive: 3.5+), have completed their last degree within the past 6 years, not have been resident in Germany for more than 15 months, and demonstrate English (IELTS 6.0+) or German language proficiency. Application deadline: October 31 annually.",
    applicationUrl: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "DAAD Development-Related Postgraduate Courses (EPOS)",
    provider: "DAAD (German Academic Exchange Service)",
    providerType: "government" as const,
    value: 992,
    currency: "EUR",
    eligibleFields: [
      "Development Studies",
      "International Development",
      "Sustainable Development",
      "Public Health",
      "Environmental Management",
      "Agriculture",
    ],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-11-30").toISOString(),
    studyLevels: ["Postgraduate"],
    eligibilityCriteria: {
      level: "Master's degree in development-related fields",
      academicRequirement: "Bachelor's degree with strong academic performance",
      workExperience: "Minimum 2 years of professional experience after bachelor's degree",
      targetCountries: "Primarily for applicants from developing countries",
      coverage: "€992/month stipend + full tuition + travel + insurance + study allowances",
      deadlineNote: "Varies by program (typically August–November)",
    },
    description:
      "DAAD Development-Related Postgraduate Courses (EPOS) provide scholarships for professionals from developing countries to pursue master's degrees in development-related fields at German universities. Scholarships cover a monthly stipend of €992, full tuition, travel, health/accident/liability insurance, and study allowances. Applicants must hold a bachelor's degree with strong academic performance, have at least 2 years of full-time professional experience after their bachelor's, and meet program-specific language requirements. Deadlines vary by program (typically August–November).",
    applicationUrl: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50076777",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Chevening Scholarships",
    provider: "UK Foreign, Commonwealth & Development Office (FCDO)",
    providerType: "government" as const,
    value: 0,
    currency: "GBP",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-10-07").toISOString(),
    studyLevels: ["Postgraduate"],
    eligibilityCriteria: {
      level: "Master's degree (one-year programs)",
      academicRequirement: "Undergraduate degree qualifying for UK master's admission",
      workExperience: "Minimum 2,800 hours (approximately 2 years full-time)",
      applicationRequirement: "Must apply to 3 different eligible UK university courses",
      bond: "Must return to home country for at least 2 years after scholarship",
      coverage: "Full tuition + monthly stipend (£1,690 London / £1,378 outside London) + travel + arrival allowance + departure allowance + visa + Chevening events",
      eligibleCountries: "160+ Chevening-eligible countries",
      universityOfferDeadline: "July 9, 2026",
    },
    description:
      "Chevening Scholarships are the UK government's global scholarship program enabling future leaders to pursue one-year master's degrees in the United Kingdom. Scholarships cover full tuition fees, monthly living stipend (£1,690 in London or £1,378 outside London), travel costs to and from the UK, arrival allowance, homeward departure allowance, one visa application cost, and travel grants for Chevening events. Applicants must hold an undergraduate degree qualifying for UK master's admission, have a minimum of 2,800 hours (approximately 2 years) of work experience, apply to 3 different eligible UK university courses, and commit to returning to their home country for at least 2 years. Application deadline: October 7, 2025 (for 2026 awards); university offer deadline: July 9, 2026.",
    applicationUrl: "https://www.chevening.org/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Commonwealth Scholarships (Master's and PhD)",
    provider: "Commonwealth Scholarship Commission (UK Foreign, Commonwealth & Development Office)",
    providerType: "government" as const,
    value: 0,
    currency: "GBP",
    eligibleFields: ["All Fields"],
    eligibleCountries: [
      "Antigua and Barbuda", "Australia", "Bangladesh", "Barbados", "Belize", "Botswana",
      "Brunei", "Cameroon", "Canada", "Cyprus", "Dominica", "Fiji", "Gambia", "Ghana",
      "Grenada", "Guyana", "India", "Jamaica", "Kenya", "Kiribati", "Lesotho", "Malawi",
      "Malaysia", "Maldives", "Malta", "Mauritius", "Mozambique", "Namibia", "Nauru",
      "New Zealand", "Nigeria", "Pakistan", "Papua New Guinea", "Rwanda", "Saint Lucia",
      "Samoa", "Seychelles", "Sierra Leone", "Singapore", "Solomon Islands", "South Africa",
      "Sri Lanka", "Saint Kitts and Nevis", "Saint Vincent and the Grenadines", "Swaziland",
      "Tanzania", "Tonga", "Trinidad and Tobago", "Tuvalu", "Uganda", "United Kingdom",
      "Vanuatu", "Zambia", "Zimbabwe",
    ],
    deadline: new Date("2026-10-14").toISOString(),
    studyLevels: ["Postgraduate", "PhD"],
    eligibilityCriteria: {
      level: "Master's degree, PhD",
      nationality: "Citizen or permanent resident of Commonwealth country, refugee, or British-protected person",
      academicRequirement: "Upper second-class (2:1) honours degree or equivalent; for PhD: appropriate master's degree",
      financialNeed: "Unable to afford UK study without scholarship",
      availability: "Must be available to start studies by September 2026",
      coverage: "Full tuition + £1,378/month living allowance + economy-class return airfare + essential expenditure grants + thesis/research grants (PhD)",
      priorityAreas: "Development-focused fields",
      resultsTimeline: "Results by July 2026",
    },
    description:
      "Commonwealth Scholarships support students from Commonwealth countries who cannot afford to study in the UK. The program covers full tuition fees, a monthly living allowance of £1,378, economy-class return airfare, grants for essential expenditures, and thesis/research grants for PhD candidates. Applicants must be citizens or permanent residents of a Commonwealth country (or refugees/British-protected persons), hold an upper second-class (2:1) honours degree or equivalent (for master's) or an appropriate master's degree (for PhD), demonstrate financial need, and be available to start studies by September 2026. The program prioritizes scholars with potential to contribute to development in their home countries. Application deadline: October 14 annually; results by July.",
    applicationUrl: "https://cscuk.fcdo.gov.uk/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Australia Awards Scholarships",
    provider: "Australian Government Department of Foreign Affairs and Trade (DFAT)",
    providerType: "government" as const,
    value: 0,
    currency: "AUD",
    eligibleFields: ["All Fields"],
    eligibleCountries: [
      "Bangladesh", "Bhutan", "Cambodia", "Fiji", "Indonesia", "Kiribati", "Laos",
      "Malaysia", "Maldives", "Marshall Islands", "Micronesia", "Mongolia", "Myanmar",
      "Nauru", "Nepal", "Pakistan", "Palau", "Papua New Guinea", "Philippines",
      "Samoa", "Solomon Islands", "Sri Lanka", "Thailand", "Timor-Leste", "Tonga",
      "Tuvalu", "Vanuatu", "Vietnam",
    ],
    deadline: new Date("2026-04-30").toISOString(),
    studyLevels: ["Undergraduate", "Postgraduate", "PhD"],
    eligibilityCriteria: {
      level: "Undergraduate, Master's degree, PhD",
      age: "Minimum 18 years",
      nationality: "Citizen of participating Indo-Pacific country, residing in and applying from home country",
      exclusions: "Not Australian citizen/permanent resident; not married to or engaged to Australian/NZ citizen; not applying for lower academic level than already achieved",
      coverage: "Full tuition + return airfare + AUD 3,000–3,500/month living allowance + Overseas Student Health Cover (OSHC) + establishment allowance + fieldwork allowance (research students)",
      priorityAreas: "Development-related fields",
      countrySpecific: "Meet country-specific criteria",
      commencementYear: "2027 (for most countries)",
    },
    description:
      "Australia Awards Scholarships provide opportunities for people from developing countries in the Indo-Pacific region to undertake full-time undergraduate or postgraduate study at participating Australian universities. Scholarships cover full tuition fees, return airfare to Australia, monthly living allowance of AUD 3,000–3,500, Overseas Student Health Cover (OSHC), establishment allowance, and fieldwork allowance for research students. Applicants must be at least 18 years old, citizens of a participating country residing in and applying from their home country, not Australian citizens or permanent residents, not married to or engaged to an Australian or New Zealand citizen, and not applying for a lower academic level than already achieved. The program aims to contribute to the development needs of partner countries. Application deadline: April 30, 2026 (for 2027 commencement in most countries).",
    applicationUrl: "https://www.dfat.gov.au/people-to-people/australia-awards",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Rotary Peace Fellowships",
    provider: "The Rotary Foundation / Rotary International",
    providerType: "foundation" as const,
    value: 0,
    currency: "USD",
    eligibleFields: [
      "Peace and Conflict Resolution",
      "International Relations",
      "Development",
      "Conflict Studies",
      "Peace Studies",
    ],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-05-31").toISOString(),
    studyLevels: ["Postgraduate", "Professional Development Certificate"],
    eligibilityCriteria: {
      level: "Master's degree or Professional Development Certificate",
      academicRequirement: "Master's program: Bachelor's degree + 3 years related work experience; Certificate program: 5 years related work experience",
      englishRequirement: "English proficiency required",
      commitment: "Strong commitment to peace demonstrated through professional/academic achievements and community service",
      skills: "Leadership skills and cross-cultural understanding",
      coverage: "Full tuition and fees + room and board + round-trip transportation + internship and field-study expenses",
      annualAwards: "Up to 130 fellowships (up to 50 for master's, 80 for certificates)",
      districtEndorsement: "District endorsements by July 1, 2026",
      resultsTimeline: "Results announced November 2026",
    },
    description:
      "Rotary Peace Fellowships support leaders with work experience in peace and development who are committed to community and international service. Up to 130 fellowships are awarded annually (up to 50 for master's degrees, 80 for professional development certificates) at Rotary Peace Centers worldwide. Fellowships cover full tuition and fees, room and board, round-trip transportation, and internship/field-study expenses. Master's applicants must hold a bachelor's degree plus 3 years of related work experience; certificate applicants need 5 years of related work experience. Candidates must demonstrate English proficiency, a strong commitment to peace through professional/academic achievements and community service, leadership skills, and cross-cultural understanding. Applications open February 2026; deadline: May 31, 2026; district endorsements by July 1, 2026; results announced November 2026.",
    applicationUrl: "https://www.rotary.org/en/our-programs/peace-fellowships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Manaaki New Zealand Scholarships",
    provider: "New Zealand Government / Education New Zealand",
    providerType: "government" as const,
    value: 0,
    currency: "NZD",
    eligibleFields: [
      "Science",
      "Engineering",
      "Medicine",
      "Arts",
      "Law",
      "Economics",
      "Management",
      "Social Sciences",
      "Technology",
      "Environmental Studies",
    ],
    eligibleCountries: [
      "Bangladesh", "Bhutan", "Cambodia", "Fiji", "Indonesia", "Jordan", "Kiribati",
      "Laos", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nauru", "Nepal", "Niue",
      "Papua New Guinea", "Philippines", "Samoa", "Solomon Islands", "Sri Lanka",
      "Thailand", "Timor-Leste", "Tonga", "Tuvalu", "Vanuatu", "Vietnam", "Cook Islands",
    ],
    deadline: new Date("2026-03-31").toISOString(),
    studyLevels: ["Undergraduate", "Postgraduate", "PhD"],
    eligibilityCriteria: {
      level: "Undergraduate, Master's degree, PhD",
      age: "Minimum 18 years",
      nationality: "Citizenship from eligible developing country",
      workExperience: "Postgraduate: 1 year full-time or 2 years part-time work experience",
      academicRequirement: "Meet academic and English language requirements of institution",
      exclusions: "Not previously received Manaaki scholarship",
      coverage: "Full tuition + NZ$531/week living allowance + NZ$3,000 establishment allowance + medical insurance + travel + family visit travel (programs > 1.6 years) + tutoring costs up to NZ$1,000 + NZ$1,000 reintegration allowance",
    },
    description:
      "Manaaki New Zealand Scholarships are funded by the New Zealand Government to support sustainable development and strengthen global partnerships. The program provides fully-funded opportunities for students from eligible developing countries in the Pacific, Southeast Asia, South Asia (excludes Pakistan and India for some programs), Mongolia, Jordan, and Timor-Leste. Scholarships cover full tuition fees, a weekly living allowance of NZ$531, a NZ$3,000 establishment allowance, medical insurance, travel to and from the home country, family visit travel for programs exceeding 1.6 years, tutoring costs up to NZ$1,000, and a NZ$1,000 reintegration allowance. Postgraduate applicants must have 1 year of full-time or 2 years of part-time work experience. Application deadline: March 31, 2026.",
    applicationUrl: "https://www.nzscholarships.govt.nz/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "France Excellence Eiffel Scholarship Program",
    provider: "French Ministry for Europe and Foreign Affairs",
    providerType: "government" as const,
    value: 1200,
    currency: "EUR",
    eligibleFields: [
      "Biology",
      "Health",
      "Ecological Transition",
      "Mathematics",
      "Digital",
      "Engineering",
      "French Language",
      "History",
      "Civilization",
      "Law",
      "Political Sciences",
      "Economics",
      "Management",
    ],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-01-08").toISOString(),
    studyLevels: ["Postgraduate", "PhD"],
    eligibilityCriteria: {
      level: "Master's degree, PhD",
      age: "Master's: born after March 31, 1996 (under 29); PhD: born after March 31, 1990 (under 35)",
      nationality: "Non-French (no dual French nationals)",
      residency: "Master's: residing outside France at application; PhD: may already be in France",
      applicationMethod: "Cannot apply directly — must be nominated by French institution",
      exclusions: "Not enrolled in continuous education/apprenticeship; not receiving other French government scholarship",
      coverage: "Master's: €1,200/month; PhD: €2,100/month + international/domestic airfare + health/social insurance + accommodation assistance. NOTE: Does NOT cover tuition fees (public university students often exempt as BGF status holders)",
      institutionDeadline: "Institutions submit to Campus France by January 8, 2026",
      resultsTimeline: "Results from March 30, 2026",
    },
    description:
      "The Eiffel Excellence Scholarship Program enables French higher education institutions to attract top international students to enroll in master's and PhD programs in Science/Techniques (Biology/Health, Ecological Transition, Mathematics/Digital, Engineering) and Human/Social Sciences (French Language/History/Civilization, Law/Political Sciences, Economics/Management). Master's scholars receive €1,200/month and must be under 29 years old; PhD scholars receive €2,100/month and must be under 35. The scholarship includes international and domestic airfare, health and social insurance, and accommodation assistance, but does NOT cover tuition fees (though students at public universities are often exempt as Boursiers du Gouvernement Français [BGF] status holders). Applicants must be non-French citizens (no dual nationals) and cannot apply directly — they must be nominated by a French institution. Institution deadline: January 8, 2026; results from March 30, 2026.",
    applicationUrl: "https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Chinese Government Scholarship (CSC)",
    provider: "China Scholarship Council / Ministry of Education of China",
    providerType: "government" as const,
    value: 2500,
    currency: "CNY",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-02-08").toISOString(),
    studyLevels: ["Undergraduate", "Postgraduate", "PhD"],
    eligibilityCriteria: {
      level: "Undergraduate, Master's degree, PhD, Chinese language programs",
      nationality: "Non-Chinese citizen in good health",
      age: "Undergraduate under 25; Master's under 35; PhD under 40",
      academicRequirement: "High school diploma for undergraduate; bachelor's for master's; master's for PhD",
      languageRequirement: "HSK Level 4 for Chinese-taught programs; TOEFL 80+/IELTS 6.0+ for English-taught programs",
      new2026: "Undergraduate applicants must take CSCA Academic Test",
      exclusions: "Cannot hold another Chinese government scholarship",
      coverage: "Full tuition + free accommodation or housing allowance + monthly stipend (Undergraduate CNY 2,500; Master's CNY 3,000; PhD CNY 3,500) + health insurance. NOTE: International airfare NOT typically covered",
      institutionCount: "Over 270 Chinese universities participate",
      deadlineNote: "Varies by application track and institution",
    },
    description:
      "The Chinese Government Scholarship (China Scholarship Council - CSC) supports international students to study at over 270 Chinese universities across all academic levels. Scholarships cover full tuition, free accommodation or housing allowance, monthly stipend (Undergraduate CNY 2,500; Master's CNY 3,000; PhD CNY 3,500), and health insurance (note: international airfare is NOT typically covered). Applicants must be non-Chinese citizens in good health, under the age limits (undergraduate under 25; master's under 35; PhD under 40), hold the required prior degree, and meet language requirements (HSK Level 4 for Chinese-taught programs; TOEFL 80+/IELTS 6.0+ for English-taught programs). NEW in 2026: undergraduate applicants must take the CSCA Academic Test. Multiple application tracks are available through embassies, government agencies, or universities directly. Application deadline: February 8, 2026 (varies by track and institution).",
    applicationUrl: "https://www.campuschina.org/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Türkiye Bursları (Turkey Scholarships)",
    provider: "Turkish Government / Presidency for Turks Abroad and Related Communities",
    providerType: "government" as const,
    value: 3500,
    currency: "TRY",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-02-20").toISOString(),
    studyLevels: ["Undergraduate", "Postgraduate", "PhD"],
    eligibilityCriteria: {
      level: "Undergraduate, Master's degree, PhD, Research",
      nationality: "Non-Turkish citizen (no dual nationals)",
      age: "Undergraduate under 21; Master's under 30; PhD under 35; Research under 50",
      academicRequirement: "Minimum 70% for undergraduate; 75% for graduate; 90% for health sciences (Medicine/Dentistry/Pharmacy)",
      residency: "Not currently studying in Turkey at same education level",
      languageRequirement: "English proficiency for English-taught programs (TOEFL/IELTS); 1-year mandatory Turkish language course (TÖMER) for all scholars before degree studies",
      coverage: "Full tuition (100%) + free accommodation in state dormitories + monthly stipend (Undergraduate TRY 3,500; Master's TRY 5,000; PhD TRY 6,500) + full health insurance + round-trip flight ticket (arrival and graduation) + 1 year free Turkish language course (TÖMER) + free academic and cultural programs",
      acceptanceRate: "3-4% (highly competitive)",
    },
    description:
      "Türkiye Bursları is the Turkish Government's fully-funded scholarship program for international students from all countries. All scholars must complete a mandatory 1-year Turkish language program (TÖMER) before starting their degree. Scholarships cover full tuition (100%), free accommodation in state dormitories, monthly stipend (Undergraduate TRY 3,500; Master's TRY 5,000; PhD TRY 6,500), full health insurance, round-trip flight ticket (arrival and graduation), 1 year of free Turkish language courses, and free academic and cultural programs. Applicants must be non-Turkish citizens (no dual nationals), under age limits (undergraduate under 21; master's under 30; PhD under 35; research under 50), meet minimum academic percentages (70% undergraduate; 75% graduate; 90% health sciences), not currently studying in Turkey at the same level, and demonstrate English proficiency for English-taught programs. Highly competitive with 3-4% acceptance rate. Deadline: February 20, 2026.",
    applicationUrl: "https://www.turkiyeburslari.gov.tr/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Global Korea Scholarship (GKS)",
    provider: "Korean Government / National Institute for International Education (NIIED)",
    providerType: "government" as const,
    value: 0,
    currency: "KRW",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2026-03-31").toISOString(),
    studyLevels: ["Undergraduate", "Postgraduate", "PhD"],
    eligibilityCriteria: {
      level: "Undergraduate, Master's degree, PhD",
      nationality: "Citizens of 155 countries (neither applicant nor parents can be Korean citizens)",
      age: "Undergraduate under 25 (born after March 1, 2001); Graduate under 40 (born after Sept 1, 1985)",
      academicRequirement: "Bachelor's degree for master's; master's degree for PhD",
      gpa: "80%+ on 100-point scale, top 20% of class, or minimum 2.64/4.0",
      health: "Physically and mentally fit",
      exclusions: "Not previously received GKS scholarship",
      languageRequirement: "Not required initially — 1-year Korean language training provided",
      coverage: "Full tuition (100%) + round-trip economy airfare + settlement allowance (one-time) + monthly living allowance + 1-year Korean language training (funded) + health insurance + completion grant + Korean Proficiency Grant (bonus for passing TOPIK)",
      applicationTracks: "Embassy Track or University Track",
      annualAwards: "Over 2,000 international students from 155 countries",
      deadlineNote: "Varies by track; consult Korean Embassy or Study in Korea website",
    },
    description:
      "The Global Korea Scholarship (GKS), formerly Korean Government Scholarship Program (KGSP), is South Korea's comprehensive government scholarship program selecting over 2,000 international students from 155 countries annually. Two application tracks are available: Embassy Track or University Track. All scholars complete a mandatory 1-year Korean language training program before degree studies. Scholarships cover full tuition (100%), round-trip economy airfare, settlement allowance (one-time), monthly living allowance, 1-year Korean language training (funded), health insurance, completion grant, and Korean Proficiency Grant (bonus for passing TOPIK). Applicants must be citizens of eligible countries (neither applicant nor parents can be Korean citizens), under age limits (undergraduate under 25; graduate under 40), hold the required prior degree, meet GPA requirements (80%+ on 100-point scale, top 20%, or minimum 2.64/4.0), and be physically and mentally fit. Application deadlines vary by track; consult the Korean Embassy or Study in Korea website.",
    applicationUrl: "https://www.studyinkorea.go.kr/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
