export const GCC_SCHOLARSHIPS = [
  {
    name: "KAUST Fellowship",
    provider: "King Abdullah University of Science and Technology",
    providerType: "university" as const,
    value: 50000,
    currency: "USD",
    eligibleFields: ["Engineering", "Science", "Computer Science", "Biological Sciences", "Physical Sciences", "Earth Sciences"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2024-12-01").toISOString(),
    eligibilityCriteria: {
      degree: "Bachelor's or Master's degree",
      minGPA: 3.5,
      languageRequirement: "TOEFL 79+ or IELTS 6.5+",
    },
    description: "The KAUST Fellowship is the general scholarship program for all Master's and PhD students. It covers full tuition, monthly living stipend ($20,000-$30,000 annually), on-campus housing, medical and dental coverage, and relocation support. KAUST is a graduate-level research university providing a world-class environment for scientific discovery.",
    applicationUrl: "https://www.kaust.edu.sa/en/admissions/guide/fellowship",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "KFUPM Graduate Scholarship",
    provider: "King Fahd University of Petroleum and Minerals",
    providerType: "university" as const,
    value: 20000,
    currency: "USD",
    eligibleFields: ["Petroleum Engineering", "Chemical Engineering", "Mechanical Engineering", "Electrical Engineering", "Civil Engineering", "Computer Science", "Mathematics"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2024-09-30").toISOString(),
    eligibilityCriteria: {
      degree: "Bachelor's degree for Master's, Master's for PhD",
      minGPA: 3.0,
      languageRequirement: "IELTS 6.0+ or TOEFL 70+",
    },
    description: "KFUPM offers fully funded scholarships for outstanding graduate students. Benefits include full tuition waiver, a monthly stipend to cover living expenses, free furnished air-conditioned bachelor housing, essential medical care, free textbooks, and subsidized meals in the University cafeteria.",
    applicationUrl: "https://admissions.kfupm.edu.sa/graduate-programs",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "King Abdulaziz University International Scholarship",
    provider: "King Abdulaziz University",
    providerType: "university" as const,
    value: 15000,
    currency: "USD",
    eligibleFields: ["Medicine", "Engineering", "Science", "Arts & Humanities", "Business Administration"],
    eligibleCountries: ["All Countries (except Saudi Arabia)"],
    deadline: new Date("2024-12-31").toISOString(),
    eligibilityCriteria: {
      ageLimit: "Under 25 for Bachelors, Under 30 for Masters, Under 35 for PhD",
      languageRequirement: "Proficiency in Arabic or English depending on the program",
    },
    description: "King Abdulaziz University offers fully funded scholarships for international students from all over the world. The scholarship includes a monthly stipend, preparation allowance when arriving for the first time, healthcare, accommodation, and annual travel tickets between Saudi Arabia and the student's home country.",
    applicationUrl: "https://scholarship.kau.edu.sa/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Qatar University International Student Scholarship",
    provider: "Qatar University",
    providerType: "university" as const,
    value: 25000,
    currency: "USD",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["All Countries (except Qatar)"],
    deadline: new Date("2024-11-15").toISOString(),
    eligibilityCriteria: {
      highSchoolGrade: "Minimum 95%",
      languageRequirement: "English or Arabic proficiency",
    },
    description: "This scholarship is awarded to applicants from outside Qatar who are talented and have high academic achievements. It covers tuition fees, textbook fees, a monthly stipend, student housing (two students per room), and annual round-trip airfare.",
    applicationUrl: "http://www.qu.edu.qa/students/admission/scholarships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "HBKU Graduate Scholarship",
    provider: "Hamad Bin Khalifa University",
    providerType: "university" as const,
    value: 30000,
    currency: "USD",
    eligibleFields: ["Public Policy", "Islamic Studies", "Science & Engineering", "Health & Life Sciences", "Humanities & Social Sciences"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2025-02-01").toISOString(),
    eligibilityCriteria: {
      degree: "Bachelor's degree with high GPA",
      languageRequirement: "IELTS 6.5+ or TOEFL 80+",
    },
    description: "HBKU offers merit-based scholarships to students enrolled in its graduate programs. These scholarships support high-achieving students by covering tuition fees and providing a competitive monthly stipend to support living costs in Doha. HBKU is part of Qatar Foundation's Education City.",
    applicationUrl: "https://www.hbku.edu.qa/en/admissions/financial-aid",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Qatar Foundation Merit Scholarship",
    provider: "Qatar Foundation",
    providerType: "foundation" as const,
    value: 40000,
    currency: "USD",
    eligibleFields: ["All Fields"],
    eligibleCountries: ["Qatar", "All Countries"],
    deadline: new Date("2025-05-31").toISOString(),
    eligibilityCriteria: {
      enrolled: "Must be a student in one of Education City's universities",
      minGPA: 3.6,
    },
    description: "The QF Merit Scholarship is awarded to undergraduate students who have demonstrated exceptional academic performance after at least two semesters of study at one of the Education City universities (CMU-Q, TAMU-Q, GU-Q, WCM-Q, VCUarts Qatar, or NU-Q). It covers tuition and other academic fees.",
    applicationUrl: "https://www.qf.org.qa/education/higher-education/financial-aid",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "King Saud University Graduate Scholarship",
    provider: "King Saud University",
    providerType: "university" as const,
    value: 18000,
    currency: "USD",
    eligibleFields: ["Engineering", "Science", "Agriculture", "Medicine", "Arts", "Education"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2024-10-31").toISOString(),
    eligibilityCriteria: {
      degree: "Relevant Bachelor's or Master's degree",
      languageRequirement: "English or Arabic proficiency",
    },
    description: "King Saud University provides full scholarships for international graduate students. The program covers all tuition fees and offers a monthly allowance, housing, and health insurance. KSU is the first university established in Saudi Arabia and remains a leader in research and education.",
    applicationUrl: "https://graduate.ksu.edu.sa/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "University of Bahrain Excellence Scholarship",
    provider: "University of Bahrain",
    providerType: "university" as const,
    value: 12000,
    currency: "USD",
    eligibleFields: ["Business Administration", "Engineering", "Information Technology", "Science", "Arts"],
    eligibleCountries: ["Bahrain", "GCC Countries"],
    deadline: new Date("2024-08-15").toISOString(),
    eligibilityCriteria: {
      highSchoolGrade: "Minimum 90%",
      nationality: "Preference for Bahraini and GCC nationals",
    },
    description: "The University of Bahrain offers merit-based scholarships for outstanding high school graduates. These awards cover tuition fees and aim to encourage academic excellence among the youth in Bahrain and the wider Gulf region.",
    applicationUrl: "http://www.uob.edu.bh/en/admission/",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "Kuwait University Graduate Assistantship",
    provider: "Kuwait University",
    providerType: "university" as const,
    value: 15000,
    currency: "USD",
    eligibleFields: ["Engineering", "Science", "Business Administration", "Social Sciences", "Law"],
    eligibleCountries: ["All Countries"],
    deadline: new Date("2024-11-30").toISOString(),
    eligibilityCriteria: {
      degree: "Bachelor's degree with high GPA",
      languageRequirement: "Proficiency in English or Arabic",
    },
    description: "Kuwait University offers graduate assistantships and financial aid to eligible Master's and PhD students. These roles involve research or teaching assistance and provide a monthly stipend that covers living expenses and tuition support.",
    applicationUrl: "https://ku.edu.kw/en/graduate-studies",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: "AUM Merit Scholarship",
    provider: "American University of the Middle East",
    providerType: "university" as const,
    value: 20000,
    currency: "USD",
    eligibleFields: ["Engineering", "Business Administration"],
    eligibleCountries: ["Kuwait", "All Countries"],
    deadline: new Date("2024-09-15").toISOString(),
    eligibilityCriteria: {
      highSchoolGrade: "Minimum 95%",
      languageRequirement: "TOEFL or IELTS",
    },
    description: "AUM offers competitive merit scholarships to high-achieving school leavers entering its undergraduate programs. The scholarship recognizes academic excellence and supports students in pursuing world-class degrees in Engineering and Business in Kuwait.",
    applicationUrl: "https://www.aum.edu.kw/admissions/scholarships",
    status: "active" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
