// Comprehensive Malaysian Boarding School Data
// Sources: MOE Malaysia, MARA, Wikipedia, ecentral.my

const now = new Date().toISOString();

export const boardingSchoolsData = [
  // ============================================================
  // SBP PREMIER (5 schools - the elite founding boarding schools)
  // ============================================================
  {
    name: "Malay College Kuala Kangsar (MCKK)",
    shortName: "MCKK",
    category: "SBP Premier" as const,
    state: "Perak",
    district: "Kuala Kangsar",
    gender: "male" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Founded in 1905, the oldest and most prestigious Malay boarding school. Known as 'Eton of the East'.",
    specialPrograms: ["Science Stream", "Arts Stream"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Tuanku Abdul Rahman (STAR)",
    shortName: "STAR",
    category: "SBP Premier" as const,
    state: "Perak",
    district: "Ipoh",
    gender: "male" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Premier all-boys boarding school established in 1961. Strong academic and co-curricular tradition.",
    specialPrograms: ["Science Stream", "Arts Stream"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Tun Fatimah (STF)",
    shortName: "STF",
    category: "SBP Premier" as const,
    state: "Johor",
    district: "Johor Bahru",
    gender: "female" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Premier all-girls boarding school established in 1958. Known for academic excellence and strong alumnae network.",
    specialPrograms: ["Science Stream", "Arts Stream"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Dato' Abdul Razak (SDAR)",
    shortName: "SDAR",
    category: "SBP Premier" as const,
    state: "Negeri Sembilan",
    district: "Seremban",
    gender: "male" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Premier all-boys boarding school established in 1956. Strong tradition of producing national leaders.",
    specialPrograms: ["Science Stream", "Arts Stream"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Tun Abdul Razak (SSTTAR)",
    shortName: "SSTTAR",
    category: "SBP Premier" as const,
    state: "Perak",
    district: "Perak Tengah",
    gender: "female" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Premier all-girls boarding school. Strong focus on academic excellence and holistic development.",
    specialPrograms: ["Science Stream", "Arts Stream"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================
  // SEKOLAH MENENGAH SAINS (SMS) - Science Secondary Schools
  // ============================================================
  {
    name: "Sekolah Menengah Sains Kuching",
    shortName: "SMSK",
    category: "SMS" as const,
    state: "Sarawak",
    district: "Kuching",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Premier science school in Sarawak. Focus on STEM education.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Lahad Datu",
    shortName: "SMSLD",
    category: "SMS" as const,
    state: "Sabah",
    district: "Lahad Datu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science boarding school serving East Malaysia students.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Hulu Selangor",
    shortName: "SMSHS",
    category: "SMS" as const,
    state: "Selangor",
    district: "Hulu Selangor",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in Selangor with strong academic track record.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Muzaffar Syah",
    shortName: "MOZAC",
    category: "SMS" as const,
    state: "Melaka",
    district: "Melaka Tengah",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Known as MOZAC. Leading science school in Melaka.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Tengku Muhammad Faris Petra",
    shortName: "SMSTMFP",
    category: "SMS" as const,
    state: "Kelantan",
    district: "Kota Bharu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in Kelantan with strong UPSR achievers.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Sultan Haji Ahmad Shah",
    shortName: "SMSSHAS",
    category: "SMS" as const,
    state: "Pahang",
    district: "Kuantan",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Top science school in Pahang state.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Tuanku Jaafar",
    shortName: "SMSTJ",
    category: "SMS" as const,
    state: "Negeri Sembilan",
    district: "Kuala Pilah",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in Negeri Sembilan with modern facilities.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Selangor",
    shortName: "SMSS",
    category: "SMS" as const,
    state: "Selangor",
    district: "Kuala Langat",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "One of the top-performing science schools in the country.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Machang",
    shortName: "SMACH",
    category: "SMS" as const,
    state: "Kelantan",
    district: "Machang",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in northern Kelantan.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Kepala Batas",
    shortName: "SMSKB",
    category: "SMS" as const,
    state: "Pulau Pinang",
    district: "Kepala Batas",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Top science school in Penang region.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Pokok Sena",
    shortName: "SMSPS",
    category: "SMS" as const,
    state: "Kedah",
    district: "Pokok Sena",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in Kedah with consistent SPM results.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Rembau",
    shortName: "SMSR",
    category: "SMS" as const,
    state: "Negeri Sembilan",
    district: "Rembau",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in Rembau, Negeri Sembilan.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Muar",
    shortName: "SMSM",
    category: "SMS" as const,
    state: "Johor",
    district: "Muar",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in Muar, Johor.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Kuala Terengganu",
    shortName: "SMSKT",
    category: "SMS" as const,
    state: "Terengganu",
    district: "Kuala Terengganu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in Terengganu state capital.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Sabah",
    shortName: "SMSS Sabah",
    category: "SMS" as const,
    state: "Sabah",
    district: "Kota Kinabalu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Premier science school in Sabah.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Sultan Mahmud",
    shortName: "SMSSM",
    category: "SMS" as const,
    state: "Terengganu",
    district: "Kuala Terengganu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school named after the Sultan of Terengganu.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Tapah",
    shortName: "SMST",
    category: "SMS" as const,
    state: "Perak",
    district: "Tapah",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Science school in Tapah, Perak.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================
  // SBPI - Sekolah Berasrama Penuh Integrasi
  // ============================================================
  {
    name: "Sekolah Berasrama Penuh Integrasi Temerloh",
    shortName: "SBPI Temerloh",
    category: "SBPI" as const,
    state: "Pahang",
    district: "Temerloh",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Integration boarding school combining academic and Islamic education.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Berasrama Penuh Integrasi Rawang",
    shortName: "SBPI Rawang",
    category: "SBPI" as const,
    state: "Selangor",
    district: "Gombak",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Integration boarding school in Rawang area.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Berasrama Penuh Integrasi Gopeng",
    shortName: "SBPI Gopeng",
    category: "SBPI" as const,
    state: "Perak",
    district: "Gopeng",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Integration boarding school in Gopeng, Perak.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Berasrama Penuh Integrasi Kubang Pasu",
    shortName: "SBPI Kubang Pasu",
    category: "SBPI" as const,
    state: "Kedah",
    district: "Kubang Pasu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Integration boarding school in Jitra, Kedah.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Berasrama Penuh Integrasi Gombak",
    shortName: "SBPI Gombak",
    category: "SBPI" as const,
    state: "Selangor",
    district: "Gombak",
    gender: "female" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "All-girls integration boarding school in Gombak.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Berasrama Penuh Integrasi Jempol",
    shortName: "SBPI Jempol",
    category: "SBPI" as const,
    state: "Negeri Sembilan",
    district: "Jempol",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Integration boarding school in Jempol, Negeri Sembilan.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Berasrama Penuh Integrasi Batu Rakit",
    shortName: "SBPI Batu Rakit",
    category: "SBPI" as const,
    state: "Terengganu",
    district: "Kuala Nerus",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Integration boarding school in Terengganu.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Berasrama Penuh Integrasi Selandar",
    shortName: "SBPI Selandar",
    category: "SBPI" as const,
    state: "Melaka",
    district: "Jasin",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Integration boarding school in Melaka.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Berasrama Penuh Integrasi Sabak Bernam",
    shortName: "SBPI Sabak Bernam",
    category: "SBPI" as const,
    state: "Selangor",
    district: "Sabak Bernam",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Integration boarding school in northern Selangor.",
    specialPrograms: ["Integrated Curriculum", "Islamic Studies"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================
  // SMAP - Sekolah Menengah Agama Persekutuan
  // ============================================================
  {
    name: "Sekolah Menengah Agama Persekutuan Labu",
    shortName: "SMAP Labu",
    category: "SMAP" as const,
    state: "Negeri Sembilan",
    district: "Seremban",
    gender: "male" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Federal religious secondary school with strong Islamic and academic curriculum.",
    specialPrograms: ["Islamic Studies", "Arabic Language", "Tahfiz"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Agama Persekutuan Kajang",
    shortName: "SMAP Kajang",
    category: "SMAP" as const,
    state: "Selangor",
    district: "Kajang",
    gender: "female" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "All-girls federal religious secondary school.",
    specialPrograms: ["Islamic Studies", "Arabic Language", "Tahfiz"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================
  // TMUA - Tahfiz Model Ulul Albab
  // ============================================================
  {
    name: "Sekolah Menengah Imtiaz Yayasan Terengganu",
    shortName: "SMIYAT",
    category: "TMUA" as const,
    state: "Terengganu",
    district: "Kuala Terengganu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Tahfiz Model Ulul Albab school combining Quran memorization with science education.",
    specialPrograms: ["Ulul Albab", "Tahfiz Al-Quran", "Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Kolej Islam Sultan Alam Shah (KISAS)",
    shortName: "KISAS",
    category: "TMUA" as const,
    state: "Selangor",
    district: "Klang",
    gender: "male" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Prestigious Islamic college combining science education with Islamic studies.",
    specialPrograms: ["Ulul Albab", "Tahfiz Al-Quran", "Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Agama Persekutuan Bentong",
    shortName: "SMAP Bentong",
    category: "SMAP" as const,
    state: "Pahang",
    district: "Bentong",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Federal religious school in Bentong.",
    specialPrograms: ["Islamic Studies", "Arabic Language"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================
  // OTHER SBP (Additional boarding schools under KPM)
  // ============================================================
  {
    name: "Sekolah Seri Puteri",
    shortName: "SSP",
    category: "SBP Premier" as const,
    state: "Kuala Lumpur",
    district: "Kuala Lumpur",
    gender: "female" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Elite all-girls boarding school in the capital. Known for producing top SPM results.",
    specialPrograms: ["Science Stream", "Arts Stream"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Sultan Alam Shah (SAS)",
    shortName: "SAS",
    category: "SBP Premier" as const,
    state: "Selangor",
    district: "Putrajaya",
    gender: "male" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Premier all-boys boarding school with strong academic tradition.",
    specialPrograms: ["Science Stream", "Arts Stream"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Menengah Sains Tuanku Munawir",
    shortName: "SASER",
    category: "SMS" as const,
    state: "Negeri Sembilan",
    district: "Seremban",
    gender: "male" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Known as SASER. One of the top science schools in Malaysia with excellent SPM results.",
    specialPrograms: ["Pure Science"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sekolah Alam Shah",
    shortName: "Alam Shah",
    category: "SMS" as const,
    state: "Selangor",
    district: "Cheras",
    gender: "male" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://spskt1.moe.gov.my",
    applicationPeriod: "August - September",
    description: "Boarding school in Cheras, Selangor.",
    specialPrograms: ["Pure Science", "Arts Stream"],
    managedBy: "KPM" as const,
    status: "active" as const,
    deadline: "2026-09-07",
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================
  // MRSM PREMIER (Top-tier MARA Science Colleges)
  // ============================================================
  {
    name: "MRSM Langkawi",
    shortName: "MRSM Langkawi",
    category: "MRSM Premier" as const,
    state: "Kedah",
    district: "Langkawi",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "Premier MRSM on Langkawi island. Top-ranked MRSM with excellent A-Level results.",
    specialPrograms: ["A-Level", "IGCSE", "Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Taiping",
    shortName: "MRSM Taiping",
    category: "MRSM Premier" as const,
    state: "Perak",
    district: "Taiping",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "One of the earliest MRSMs established. Consistently top-performing.",
    specialPrograms: ["A-Level", "IGCSE", "Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Tun Abdul Razak (Pekan)",
    shortName: "MRSM Pekan",
    category: "MRSM Premier" as const,
    state: "Pahang",
    district: "Pekan",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "Named after the second Prime Minister. Premier MRSM with strong science focus.",
    specialPrograms: ["A-Level", "IGCSE", "Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Tun Ghafar Baba (Jasin)",
    shortName: "MRSM Jasin",
    category: "MRSM Premier" as const,
    state: "Melaka",
    district: "Jasin",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "Premier MRSM in Melaka. Named after former Deputy PM.",
    specialPrograms: ["A-Level", "IGCSE", "Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Sultan Azlan Shah (Kuala Kangsar)",
    shortName: "MRSM KK",
    category: "MRSM Premier" as const,
    state: "Perak",
    district: "Kuala Kangsar",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "Premier MRSM in Kuala Kangsar. Named after Sultan of Perak.",
    specialPrograms: ["A-Level", "IGCSE", "Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================
  // MRSM (Regular MRSM - All 57 campuses across Malaysia)
  // ============================================================
  // --- Johor ---
  {
    name: "MRSM Mersing",
    shortName: "MRSM Mersing",
    category: "MRSM" as const,
    state: "Johor",
    district: "Mersing",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Mersing, east coast of Johor.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Kota Tinggi",
    shortName: "MRSM Kota Tinggi",
    category: "MRSM" as const,
    state: "Johor",
    district: "Kota Tinggi",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Kota Tinggi, Johor.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Muar",
    shortName: "MRSM Muar",
    category: "MRSM" as const,
    state: "Johor",
    district: "Muar",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Muar, Johor.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Gemencheh",
    shortName: "MRSM Gemencheh",
    category: "MRSM" as const,
    state: "Negeri Sembilan",
    district: "Tampin",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Gemencheh, Negeri Sembilan.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Kedah ---
  {
    name: "MRSM Merbok",
    shortName: "MRSM Merbok",
    category: "MRSM" as const,
    state: "Kedah",
    district: "Merbok",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM near Universiti Teknologi MARA in Merbok.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Kubang Pasu",
    shortName: "MRSM Kubang Pasu",
    category: "MRSM" as const,
    state: "Kedah",
    district: "Kubang Pasu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in northern Kedah near the Thai border.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Sik",
    shortName: "MRSM Sik",
    category: "MRSM" as const,
    state: "Kedah",
    district: "Sik",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Sik, Kedah.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM PDRM Kulim",
    shortName: "MRSM PDRM Kulim",
    category: "MRSM" as const,
    state: "Kedah",
    district: "Kulim",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM primarily for children of PDRM (Royal Malaysia Police) personnel.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Kelantan ---
  {
    name: "MRSM Pengkalan Chepa",
    shortName: "MRSM PC",
    category: "MRSM" as const,
    state: "Kelantan",
    district: "Kota Bharu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Pengkalan Chepa, Kelantan.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Kuala Krai",
    shortName: "MRSM KK",
    category: "MRSM" as const,
    state: "Kelantan",
    district: "Kuala Krai",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Kuala Krai, Kelantan.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Pasir Tumboh",
    shortName: "MRSM PT",
    category: "MRSM" as const,
    state: "Kelantan",
    district: "Kota Bharu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Pasir Tumboh, Kelantan.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Melaka ---
  {
    name: "MRSM Alor Gajah",
    shortName: "MRSM AG",
    category: "MRSM" as const,
    state: "Melaka",
    district: "Alor Gajah",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Alor Gajah, Melaka.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Pahang ---
  {
    name: "MRSM Kuantan",
    shortName: "MRSM Kuantan",
    category: "MRSM" as const,
    state: "Pahang",
    district: "Kuantan",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in the state capital of Pahang.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Kuala Lipis",
    shortName: "MRSM KL",
    category: "MRSM" as const,
    state: "Pahang",
    district: "Kuala Lipis",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Kuala Lipis, Pahang.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Muadzam Shah",
    shortName: "MRSM MS",
    category: "MRSM" as const,
    state: "Pahang",
    district: "Rompin",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Muadzam Shah, Pahang.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM ATM Bera",
    shortName: "MRSM ATM Bera",
    category: "MRSM" as const,
    state: "Pahang",
    district: "Bera",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM primarily for children of Armed Forces (ATM) personnel. Opened in 2020.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Perak ---
  {
    name: "MRSM Lenggong",
    shortName: "MRSM Lenggong",
    category: "MRSM" as const,
    state: "Perak",
    district: "Lenggong",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Lenggong, Perak. Near the UNESCO World Heritage archaeological site.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Gerik",
    shortName: "MRSM Gerik",
    category: "MRSM" as const,
    state: "Perak",
    district: "Gerik",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Gerik, northern Perak.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Felda Trolak",
    shortName: "MRSM Trolak",
    category: "MRSM" as const,
    state: "Perak",
    district: "Muallim",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM serving FELDA settlement area in Trolak.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Bagan Datuk",
    shortName: "MRSM BD",
    category: "MRSM" as const,
    state: "Perak",
    district: "Bagan Datuk",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "Newest MRSM in Perak, opened 2021. Offers Ulul Albab programme.",
    specialPrograms: ["Ulul Albab", "Tahfiz Al-Quran"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Terendak",
    shortName: "MRSM Terendak",
    category: "MRSM" as const,
    state: "Melaka",
    district: "Alor Gajah",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM at Terendak military camp. Primarily for children of Armed Forces personnel.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Perlis ---
  {
    name: "MRSM Beseri",
    shortName: "MRSM Beseri",
    category: "MRSM" as const,
    state: "Perlis",
    district: "Beseri",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in the northernmost state of Peninsular Malaysia.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Pulau Pinang ---
  {
    name: "MRSM Transkerian (Balik Pulau)",
    shortName: "MRSM Balik Pulau",
    category: "MRSM" as const,
    state: "Pulau Pinang",
    district: "Balik Pulau",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM on Penang island.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Kepala Batas",
    shortName: "MRSM Kepala Batas",
    category: "MRSM" as const,
    state: "Pulau Pinang",
    district: "Kepala Batas",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in mainland Penang.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Selangor ---
  {
    name: "MRSM Tanjung Karang",
    shortName: "MRSM TK",
    category: "MRSM" as const,
    state: "Selangor",
    district: "Kuala Selangor",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Tanjung Karang, Selangor.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Terengganu ---
  {
    name: "MRSM Kuala Terengganu",
    shortName: "MRSM KT",
    category: "MRSM" as const,
    state: "Terengganu",
    district: "Kuala Terengganu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in the state capital of Terengganu.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Besut",
    shortName: "MRSM Besut",
    category: "MRSM" as const,
    state: "Terengganu",
    district: "Besut",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Besut, northern Terengganu.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Dungun",
    shortName: "MRSM Dungun",
    category: "MRSM" as const,
    state: "Terengganu",
    district: "Dungun",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Dungun, Terengganu.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Sabah ---
  {
    name: "MRSM Kota Kinabalu",
    shortName: "MRSM KK Sabah",
    category: "MRSM" as const,
    state: "Sabah",
    district: "Kota Kinabalu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in the capital of Sabah.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Sandakan",
    shortName: "MRSM Sandakan",
    category: "MRSM" as const,
    state: "Sabah",
    district: "Sandakan",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Sandakan, Sabah.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Tawau",
    shortName: "MRSM Tawau",
    category: "MRSM" as const,
    state: "Sabah",
    district: "Tawau",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Tawau, southeastern Sabah.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Semporna",
    shortName: "MRSM Semporna",
    category: "MRSM" as const,
    state: "Sabah",
    district: "Semporna",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Semporna, Sabah.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Sarawak ---
  {
    name: "MRSM Kuching",
    shortName: "MRSM Kuching",
    category: "MRSM" as const,
    state: "Sarawak",
    district: "Kuching",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in the capital of Sarawak.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Mukah",
    shortName: "MRSM Mukah",
    category: "MRSM" as const,
    state: "Sarawak",
    district: "Mukah",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Mukah, Sarawak.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Betong",
    shortName: "MRSM Betong",
    category: "MRSM" as const,
    state: "Sarawak",
    district: "Betong",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Betong, Sarawak.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Sibu",
    shortName: "MRSM Sibu",
    category: "MRSM" as const,
    state: "Sarawak",
    district: "Sibu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Sibu, Sarawak.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Miri",
    shortName: "MRSM Miri",
    category: "MRSM" as const,
    state: "Sarawak",
    district: "Miri",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Miri, northern Sarawak.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Negeri Sembilan ---
  {
    name: "MRSM Kuala Klawang",
    shortName: "MRSM KK NS",
    category: "MRSM" as const,
    state: "Negeri Sembilan",
    district: "Jelebu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Kuala Klawang, Negeri Sembilan.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Selangor ---
  {
    name: "MRSM Ulul Albab Puncak Alam",
    shortName: "MRSM UA PA",
    category: "MRSM" as const,
    state: "Selangor",
    district: "Kuala Selangor",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM with Ulul Albab programme combining Quran memorization with science education.",
    specialPrograms: ["Ulul Albab", "Tahfiz Al-Quran", "Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Pahang ---
  {
    name: "MRSM Bentong",
    shortName: "MRSM Bentong",
    category: "MRSM" as const,
    state: "Pahang",
    district: "Bentong",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Bentong, western Pahang.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Johor ---
  {
    name: "MRSM Johor Bahru (Taman Daya)",
    shortName: "MRSM JB",
    category: "MRSM" as const,
    state: "Johor",
    district: "Johor Bahru",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Johor Bahru city.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Batu Pahat",
    shortName: "MRSM BP",
    category: "MRSM" as const,
    state: "Johor",
    district: "Batu Pahat",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Batu Pahat, Johor.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  // --- Additional ---
  {
    name: "MRSM Pandan (Kuantan)",
    shortName: "MRSM Pandan",
    category: "MRSM" as const,
    state: "Pahang",
    district: "Kuantan",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Pandan, near Kuantan.",
    specialPrograms: ["Pure Science", "Technical"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Jeli",
    shortName: "MRSM Jeli",
    category: "MRSM" as const,
    state: "Kelantan",
    district: "Jeli",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Jeli, Kelantan.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Setiu",
    shortName: "MRSM Setiu",
    category: "MRSM" as const,
    state: "Terengganu",
    district: "Setiu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Setiu, Terengganu.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Pendang",
    shortName: "MRSM Pendang",
    category: "MRSM" as const,
    state: "Kedah",
    district: "Pendang",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Pendang, Kedah.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Pontian",
    shortName: "MRSM Pontian",
    category: "MRSM" as const,
    state: "Johor",
    district: "Pontian",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Pontian, southern Johor.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Lipis Raub",
    shortName: "MRSM LR",
    category: "MRSM" as const,
    state: "Pahang",
    district: "Raub",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Raub, Pahang.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Pasir Salak",
    shortName: "MRSM Pasir Salak",
    category: "MRSM" as const,
    state: "Perak",
    district: "Perak Tengah",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Pasir Salak, Perak. Named after the historical Pasir Salak area.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "MRSM Pengkalan Hulu",
    shortName: "MRSM PH",
    category: "MRSM" as const,
    state: "Perak",
    district: "Pengkalan Hulu",
    gender: "mixed" as const,
    entryLevels: ["Tingkatan 1", "Tingkatan 4"],
    applicationPortal: "https://mrsm.mara.gov.my/mymrsm/",
    applicationPeriod: "March - May",
    description: "MRSM in Pengkalan Hulu, northernmost Perak.",
    specialPrograms: ["Pure Science"],
    managedBy: "MARA" as const,
    status: "active" as const,
    deadline: "2026-05-31",
    createdAt: now,
    updatedAt: now,
  },
];
