export const COUNTRIES = [
  'Malaysia',
  'Singapore',
  'United Kingdom',
  'United States',
  'Australia',
  'Canada',
  'Germany',
  'Japan',
  'South Korea',
  'China',
  'India',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'France',
  'Netherlands',
  'Switzerland',
  'New Zealand',
  'Ireland',
].sort();

export const UNIVERSITIES = [
  'Universiti Malaya (UM)',
  'Universiti Kebangsaan Malaysia (UKM)',
  'Universiti Putra Malaysia (UPM)',
  'Universiti Sains Malaysia (USM)',
  'Universiti Teknologi Malaysia (UTM)',
  'Taylor\'s University',
  'Sunway University',
  'UCSI University',
  'Monash University Malaysia',
  'The University of Nottingham Malaysia',
  'Heriot-Watt University Malaysia',
  'Xiamen University Malaysia',
  'UTAR (Universiti Tunku Abdul Rahman)',
  'Multimedia University (MMU)',
  'Asia Pacific University (APU)',
  'Oxford University',
  'Cambridge University',
  'Harvard University',
  'Stanford University',
  'MIT',
  'Imperial College London',
  'University College London (UCL)',
  'National University of Singapore (NUS)',
  'Nanyang Technological University (NTU)',
  'Melbourne University',
  'Sydney University',
].sort();

export const FIELDS_OF_STUDY = [
  'Computer Science',
  'Information Technology',
  'Software Engineering',
  'Data Science',
  'Artificial Intelligence',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Medicine',
  'Pharmacy',
  'Dentistry',
  'Nursing',
  'Business Administration',
  'Accounting',
  'Finance',
  'Economics',
  'Marketing',
  'Law',
  'Psychology',
  'Architecture',
  'Graphic Design',
  'Fine Arts',
  'Mass Communication',
  'Education',
  'Environmental Science',
  'Biotechnology',
].sort();
