export const COUNTRIES = [
  'Malaysia',
  'Singapore',
  'United Kingdom',
  'United States',
  'Australia',
  'Canada',
  'Germany',
  'Japan',
  'South Korea',
  'China',
  'India',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'France',
  'Netherlands',
  'Switzerland',
  'New Zealand',
  'Ireland',
].sort();

export const UNIVERSITIES = [
  // Public Universities (20)
  'Universiti Malaya (UM)',
  'Universiti Sains Malaysia (USM)',
  'Universiti Kebangsaan Malaysia (UKM)',
  'Universiti Putra Malaysia (UPM)',
  'Universiti Teknologi Malaysia (UTM)',
  'Universiti Teknologi MARA (UiTM)',
  'Universiti Islam Antarabangsa Malaysia (IIUM)',
  'Universiti Utara Malaysia (UUM)',
  'Universiti Malaysia Sarawak (UNIMAS)',
  'Universiti Malaysia Sabah (UMS)',
  'Universiti Pendidikan Sultan Idris (UPSI)',
  'Universiti Sains Islam Malaysia (USIM)',
  'Universiti Malaysia Terengganu (UMT)',
  'Universiti Malaysia Kelantan (UMK)',
  'Universiti Malaysia Perlis (UniMAP)',
  'Universiti Sultan Zainal Abidin (UniSZA)',
  'Universiti Tun Hussein Onn Malaysia (UTHM)',
  'Universiti Teknikal Malaysia Melaka (UTeM)',
  'Universiti Pertahanan Nasional Malaysia (UPNM)',
  'Universiti Malaysia Pahang Al-Sultan Abdullah (UMPSA)',
  // Major Local Private Universities
  'Multimedia University (MMU)',
  'Universiti Tunku Abdul Rahman (UTAR)',
  'Universiti Tenaga Nasional (UNITEN)',
  'Universiti Kuala Lumpur (UniKL)',
  'Universiti Teknologi PETRONAS (UTP)',
  'Open University Malaysia (OUM)',
  'University of Selangor (UNISEL)',
  // Well-known Private Universities
  'Taylor\'s University',
  'Sunway University',
  'UCSI University',
  'Asia Pacific University of Technology & Innovation (APU)',
  'Management and Science University (MSU)',
  'SEGi University',
  // Foreign Branch Campuses in Malaysia
  'Monash University Malaysia',
  'University of Nottingham Malaysia',
  'Curtin University Malaysia',
  'Heriot-Watt University Malaysia',
  'University of Reading Malaysia',
  'Xiamen University Malaysia',
  // International Universities
  'Oxford University',
  'Cambridge University',
  'Harvard University',
  'Stanford University',
  'MIT',
  'Imperial College London',
  'University College London (UCL)',
  'National University of Singapore (NUS)',
  'Nanyang Technological University (NTU)',
  'Melbourne University',
  'Sydney University',
].sort();

export const MALAYSIAN_UNIVERSITIES: ReadonlySet<string> = new Set([
  // Public Universities
  'Universiti Malaya (UM)',
  'Universiti Sains Malaysia (USM)',
  'Universiti Kebangsaan Malaysia (UKM)',
  'Universiti Putra Malaysia (UPM)',
  'Universiti Teknologi Malaysia (UTM)',
  'Universiti Teknologi MARA (UiTM)',
  'Universiti Islam Antarabangsa Malaysia (IIUM)',
  'Universiti Utara Malaysia (UUM)',
  'Universiti Malaysia Sarawak (UNIMAS)',
  'Universiti Malaysia Sabah (UMS)',
  'Universiti Pendidikan Sultan Idris (UPSI)',
  'Universiti Sains Islam Malaysia (USIM)',
  'Universiti Malaysia Terengganu (UMT)',
  'Universiti Malaysia Kelantan (UMK)',
  'Universiti Malaysia Perlis (UniMAP)',
  'Universiti Sultan Zainal Abidin (UniSZA)',
  'Universiti Tun Hussein Onn Malaysia (UTHM)',
  'Universiti Teknikal Malaysia Melaka (UTeM)',
  'Universiti Pertahanan Nasional Malaysia (UPNM)',
  'Universiti Malaysia Pahang Al-Sultan Abdullah (UMPSA)',
  // Major Local Private Universities
  'Multimedia University (MMU)',
  'Universiti Tunku Abdul Rahman (UTAR)',
  'Universiti Tenaga Nasional (UNITEN)',
  'Universiti Kuala Lumpur (UniKL)',
  'Universiti Teknologi PETRONAS (UTP)',
  'Open University Malaysia (OUM)',
  'University of Selangor (UNISEL)',
  // Well-known Private Universities
  'Taylor\'s University',
  'Sunway University',
  'UCSI University',
  'Asia Pacific University of Technology & Innovation (APU)',
  'Management and Science University (MSU)',
  'SEGi University',
  // Foreign Branch Campuses in Malaysia
  'Monash University Malaysia',
  'University of Nottingham Malaysia',
  'Curtin University Malaysia',
  'Heriot-Watt University Malaysia',
  'University of Reading Malaysia',
  'Xiamen University Malaysia',
]);

export const LOCAL_UNIVERSITIES_BY_COUNTRY: Record<string, ReadonlySet<string>> = {
  Malaysia: MALAYSIAN_UNIVERSITIES,
};

export const INTERESTS = [
  'Artificial Intelligence',
  'Machine Learning',
  'Data Science',
  'Software Development',
  'Web Development',
  'Mobile App Development',
  'Cybersecurity',
  'Cloud Computing',
  'Blockchain',
  'Robotics',
  'Business Management',
  'Entrepreneurship',
  'Finance & Investment',
  'Marketing',
  'Economics',
  'Accounting',
  'Human Resources',
  'Supply Chain Management',
  'Medicine & Healthcare',
  'Biotechnology',
  'Environmental Science',
  'Renewable Energy',
  'Psychology',
  'Education & Teaching',
  'Law & Policy',
  'Architecture & Design',
  'Graphic Design',
  'Film & Media',
  'Music & Performing Arts',
  'Creative Writing',
].sort();

export const COUNTRY_CODES = [
  { code: '+60', country: 'Malaysia' },
  { code: '+65', country: 'Singapore' },
  { code: '+44', country: 'United Kingdom' },
  { code: '+1', country: 'United States' },
  { code: '+61', country: 'Australia' },
  { code: '+1', country: 'Canada' },
  { code: '+49', country: 'Germany' },
  { code: '+81', country: 'Japan' },
  { code: '+82', country: 'South Korea' },
  { code: '+86', country: 'China' },
  { code: '+91', country: 'India' },
  { code: '+62', country: 'Indonesia' },
  { code: '+66', country: 'Thailand' },
  { code: '+84', country: 'Vietnam' },
  { code: '+63', country: 'Philippines' },
  { code: '+33', country: 'France' },
  { code: '+31', country: 'Netherlands' },
  { code: '+41', country: 'Switzerland' },
  { code: '+64', country: 'New Zealand' },
  { code: '+353', country: 'Ireland' },
  { code: '+971', country: 'UAE' },
  { code: '+966', country: 'Saudi Arabia' },
  { code: '+974', country: 'Qatar' },
  { code: '+880', country: 'Bangladesh' },
  { code: '+92', country: 'Pakistan' },
  { code: '+94', country: 'Sri Lanka' },
  { code: '+95', country: 'Myanmar' },
  { code: '+855', country: 'Cambodia' },
  { code: '+856', country: 'Laos' },
  { code: '+673', country: 'Brunei' },
];

export const FIELDS_OF_STUDY = [
  'Computer Science',
  'Information Technology',
  'Software Engineering',
  'Data Science',
  'Artificial Intelligence',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Medicine',
  'Pharmacy',
  'Dentistry',
  'Nursing',
  'Business Administration',
  'Accounting',
  'Finance',
  'Economics',
  'Marketing',
  'Law',
  'Psychology',
  'Architecture',
  'Graphic Design',
  'Fine Arts',
  'Mass Communication',
  'Education',
  'Environmental Science',
  'Biotechnology',
].sort();
